### ISSUE TITLE
single page mode not changing the config

### ISSUE THREAD

**Issue by pawanhv** [silexlabs/Silex#1080]
I started looking into the single page mode and followed the instructions. When I start the project the index file is still the standard index file. Somehow the change configurations are not taken .

**Comment by lexoyo** [comment]
Oh ok
Could you share your test?

**Comment by pawanhv** [comment]
1. I started a node project with index.js with the following code: 
```
var serveStatic = require('serve-static')
const path = require('path');

const { SilexServer, Config } = require('silex-website-builder');

const config = new Config();
const silex = new SilexServer(config);


silex.start(function() {
  console.log('server started');
});

// serve modified html
silex.app.use('/', serveStatic(path.resolve('./dist/')));

```

2. I created the pug file

```

extends ./node_modules/silex-website-builder/src/html/index.jade
append silex-options
  script.
    silex.config.singleSiteMode = true;

```



3. Added the following code to package.json 

```
"scripts": {
        "start": "node index.js",
        "build": "npm run build:components && npm run build:html",
        "build:html": "pug index.pug -o dist/"
    }
}

```

I am probably missing something but this is the index file I am getting , I must not be expecting the save as etc.. in the menu right?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18898460/103175874-ac0b7800-486d-11eb-922e-c707d5b6617e.png">

**Comment by lexoyo** [comment]
oh ok, it looks good to me

> I am probably missing something but this is the index file I am getting , I must not be expecting the save as etc.. in the menu right?

you are correct, it is not supposed to be there

maybe for some reason silex is still serving the old HTML file. please try to build your html file as /dist/test.html and then load this file?

**Comment by lexoyo** [comment]
ok I got it: the line with `silex.app.use` needs to be before the one with `silex.start`
would you add this to the docs?

**Comment by pawanhv** [comment]
I did the changes to my code but still same index page. where can I find the logic that routes the singleSiteMode.I don't seem to find it anywhere. Maybe the nom silex version of 2.7.4 had some issues?

**Comment by lexoyo** [comment]
I just did the test and it seemed to work :-/
Here is the code I tested
http://github.com/silexlabs/custom-silex-components

**Comment by lexoyo** [comment]
And here is the logic
https://github.com/silexlabs/Silex/blob/develop/src/ts/client/App.ts#L77

**Comment by lexoyo** [comment]
I'll have time to check again tomorrow

**Comment by pawanhv** [comment]
I cleaned everything and restarted the build, now the page seems to be changed but blocked at loading..

**Comment by lexoyo** [comment]
can you check if all resources are loaded? i'll need more info
i believe you are close ;)

**Comment by pawanhv** [comment]
I get this error 

Error: Unknown connector: fs
    at Unifile.callMethod (/Users/pavanhemmege/CODE/web_editor/node_modules/unifile/lib/index.js:333:41)
    at Unifile.readdir (/Users/pavanhemmege/CODE/web_editor/node_modules/unifile/lib/index.js:204:15)
    at /Users/pavanhemmege/CODE/web_editor/node_modules/cloud-explorer/lib/router.js:206:20
    at Layer.handle [as handle_request] (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/route.js:137:13)
    at noCache (/Users/pavanhemmege/CODE/web_editor/node_modules/cloud-explorer/lib/router.js:51:3)
    at Layer.handle [as handle_request] (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/layer.js:95:5)
    at /Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:281:22
    at param (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:410:3)
    at IncomingMessage.next (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:275:10)

Error: Unknown connector: fs
    at Unifile.callMethod (/Users/pavanhemmege/CODE/web_editor/node_modules/unifile/lib/index.js:333:41)
    at Unifile.readdir (/Users/pavanhemmege/CODE/web_editor/node_modules/unifile/lib/index.js:204:15)
    at /Users/pavanhemmege/CODE/web_editor/node_modules/cloud-explorer/lib/router.js:206:20
    at Layer.handle [as handle_request] (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/route.js:137:13)
    at noCache (/Users/pavanhemmege/CODE/web_editor/node_modules/cloud-explorer/lib/router.js:51:3)
    at Layer.handle [as handle_request] (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/layer.js:95:5)
    at /Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:281:22
    at param (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:410:3)
    at IncomingMessage.next (/Users/pavanhemmege/CODE/web_editor/node_modules/express/lib/router/index.js:275:10)

**Comment by lexoyo** [comment]
ok, this is a server side error
it means you are trying to access a folder on your local file system (fs) but silex do not have this connector
this is "normal", you probably did access the local file system at one point and silex remembers it (local storage)
you can ignore this error, or enable fs like this (add this after the line `const config = new Config();`):
```js
config.ceOptions.enableFs = true;
```
For [all the options on this config object, see this file](https://github.com/silexlabs/custom-silex-components/blob/master/index.js#L7)


back to silex not loading (which is probably a client side error), look at the js console, and let me know if there is an error or what files did not load

**Comment by pawanhv** [comment]
I don't get the fs error anymore with the config enableFS .

I don't see any errors client side. but the page is still blocked in loading .


```
> web_editor@1.0.0 start /Users/pavanhemmege/CODE/web_editor
> node index.js

> FTP service disabled, env vars ENABLE_FTP not set
> SFTP service enabled
> Webdav service disabled, env vars ENABLE_WEBDAV not set
> Github service disabled, env vars GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET not set
> Dropbox service disabled, env vars DROPBOX_CLIENT_ID and DROPBOX_CLIENT_SECRET not set
> Local file system service enabled
Warning local file system is writable, use FS_ROOT as root ( /Users/pavanhemmege )

Starting. Version is 2,2,11 for the websites and 2,11 for Silex

> Adding hosting provider Choose a folder
> Force SSL option is disabled, env var SILEX_FORCE_HTTPS not set
> SSL certificate disabled, env vars SILEX_SSL_CERTIFICATE and SILEX_SSL_PRIVATE_KEY not set

I'm ready, listening to port 6805

server started
```

**Comment by lexoyo** [comment]
```
> web_editor@1.0.0 start /Users/pavanhemmege/CODE/web_editor
> node index.js

> FTP service disabled, env vars ENABLE_FTP not set
> SFTP service enabled
> Webdav service disabled, env vars ENABLE_WEBDAV not set
> Github service disabled, env vars GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET not set
> Dropbox service disabled, env vars DROPBOX_CLIENT_ID and DROPBOX_CLIENT_SECRET not set
> Local file system service enabled
Warning local file system is writable, use FS_ROOT as root ( /Users/pavanhemmege )

Starting. Version is 2,2,11 for the websites and 2,11 for Silex

> Adding hosting provider Choose a folder
> Force SSL option is disabled, env var SILEX_FORCE_HTTPS not set
> SSL certificate disabled, env vars SILEX_SSL_CERTIFICATE and SILEX_SSL_PRIVATE_KEY not set

I'm ready, listening to port 6805

server started
```
this is still server side
just to be sure I understand : you did check the [js console of your browser](https://developer.mozilla.org/en-US/docs/Tools/Web_Console)? (i'm not sure how comfortable you are on the front end)

**Comment by pawanhv** [comment]
Ah I was not thinking right for checking out the console . its been long I havent touched frontend ;)
here's the error I get

<img width="551" alt="image" src="https://user-images.githubusercontent.com/18898460/103204853-8bd4cb00-48f8-11eb-8386-7e6cad524a31.png">

**Comment by pawanhv** [comment]
here is my repo : 
https://github.com/pawanhv/silex_web_v1

**Comment by lexoyo** [comment]
Hey I tested your code, and all seem good to me
Did you try to pass `path` and `service` in the URL? When I do, I have no error anymore, i.e. `http://localhost:6805/?path=/Documents/tmp/silex_web_v1/editable.html&service=fs`

But I have something which do not work though : i need to press enter for the loading screen to go away... this is because of this alert showing up:
![Screenshot from 2020-12-28 19-29-47](https://user-images.githubusercontent.com/715377/103235726-12ae9580-4943-11eb-85c1-1f8a127b79a5.png)

So there are 2 bugs we need to fix before using the single site mode:

1. the alert should be on top of the loading screen (bug is in the CSS, z-index probably)
2. the alert should not show up (this I did not investigate yet)

**Comment by lexoyo** [comment]
for the point 2. I found that isDirty is true by default
this is because it is [initialized here](https://github.com/silexlabs/Silex/blob/develop/src/ts/client/dirty.ts#L41) with null values. so `initSingleSiteMode` should call `resetDirty()` before calling `openRecent` and no need to call `afterInit()` after calling `initSingleSiteMode` because all it does is hide loading screen (which is done by `openRecent`) and then call `resetDirty()` which we will do before...

**Comment by lexoyo** [comment]
i just published a fix on silexlabs/Silex#develop for the point 2.

**Comment by pawanhv** [comment]
> Hey I tested your code, and all seem good to me
> Did you try to pass `path` and `service` in the URL? When I do, I have no error anymore, i.e. `http://localhost:6805/?path=/Documents/tmp/silex_web_v1/editable.html&service=fs`
> 

I don't have the editable.html , am I missing something?

**Comment by lexoyo** [comment]
> > Hey I tested your code, and all seem good to me
> > Did you try to pass `path` and `service` in the URL? When I do, I have no error anymore, i.e. `http://localhost:6805/?path=/Documents/tmp/silex_web_v1/editable.html&service=fs`
> > 
> 
> I don't have the editable.html , am I missing something? 

Oh yes it is a path to a silex site
It needs to exist

**Comment by pawanhv** [comment]
I guess I am stuck , I have "silex-website-builder": "^2.7.4" installed from npm. but I don't find editable.html file in the folder. 
Is there a doc to explain this? if not I can add this info to the standalone mode documentation when I will succeed to run successfully.

**Comment by pawanhv** [comment]
Can you share your working repo so I can check :)

Pavan

**Comment by lexoyo** [comment]
Ok sure, I will share it

Here is an explanation in the meantime

1. The HTML file editable is just any template available on Silex which you can save anywhere (save it from silex on github or Dropbox or somewhere depending on what services you plan to allow on your Silex instance)
1. In order to get the fix I committed on silexlabs/Silex#develop you need to edit your package.json and replace the version with this: `silexlabs/Silex#develop` then run  an `npm install` again

**Comment by lexoyo** [comment]
Hi @pawanhv 
I think I lost my test :-/

**Comment by pawanhv** [comment]
Ah I did not succedd to go past the loading page yet. I downloaded editable.html from repo but still doesnt work .
