### ISSUE TITLE
html error #401

### ISSUE THREAD

**Issue by promoviper** [silexlabs/Silex#172]
Tried in firefox and chrome to connect to drop box and keep getting this error.  Worked initially then just quit working.

**Comment by theedoms** [comment]
Hello,
I am getting into that problem too. I installed the system on my windows7 and I tried online with dropbox as well.
Either from chrome or Mozilla I cant get the html page to appear in the editor. It keeps looping again and again...
Albeit the file has been loaded since I can preview the publish...
Any hint ?

![silexlabs silex error](https://cloud.githubusercontent.com/assets/142169/8107557/71812696-104a-11e5-900f-c3bcb04b3d2e.JPG)

**Comment by lexoyo** [comment]
Hi @theedoms 
I'm affraid you have to wait a few minutes, it is due to our hosting company, and it depends where you are (which country)
Is it fixed now?

**Comment by lexoyo** [comment]
it loads normally here in france 
![screen shot 2015-06-11 at 16 09 48](https://cloud.githubusercontent.com/assets/715377/8108977/5a665774-1054-11e5-8e29-0d24d4343d67.png)

**Comment by theedoms** [comment]
Bonjour Alex,
Je suis a Montpellier !!
J'ai le même PB sur mon PC et sur le cloud .
Hope that helps...

Dominique VERDEJO
+33 6 08579220

**Comment by theedoms** [comment]
Hi Alex,
Still not fixed.
Please have a look at the screen cam here :
https://www.dropbox.com/s/wdt0fanlwtrtca5/2015-06-11_2202_silex_bug_html_page_load.swf?dl=0
D.




*Dominique VERDEJO*
dominique.verdejo@gmail.com
mobile +33 6 08 57 92 20

14 boulevard de la République 34590 Marsillargues - FRANCE
tél +33 4 99 64 70 19 - fax: +33 9 85 92 60 14
*PERSONAL INTERACTOR <http://www.personalinteractor.net>* SIRET
42078659200030
[image: View Dominique Verdejo's profile on LinkedIn]
<http://fr.linkedin.com/in/dominiqueverdejo>

2015-06-11 16:09 GMT+02:00 Alex Hoyau <notifications@github.com>:
