### ISSUE TITLE
HTML page keeps loading 

### ISSUE THREAD

**Issue by theedoms** [silexlabs/Silex#279]
I experienced on the SaaS as well as on a windows 7 install the following bug:
The "file/open file" menu allows to select a file and starts loading it but never stops.
Nevertheless the "view/preview" menu allows to see the page...
![silexlabs silex error](https://cloud.githubusercontent.com/assets/142169/8117130/4bd468ea-1086-11e5-8d20-ba80a31a709c.JPG)

See attached screen.

**Comment by lexoyo** [comment]
Hi, thank you for the bug report

I could not reproduce it even with the same setup as you have (win7 and chrome I believe)
It is probably simply the static scripts which were unavailable at that time because they are hosted on a poor quality hosting. I will soon move them to github pages so that they are almost always available.

@theedoms can you try again and confirm that it is fixed please?

When this happens to you, please check the logs in the javascript developer console. And also, look for this status error on [Silex status twitter account](https://twitter.com/status_silex)
`** PROBLEM Alert - Silex static files is DOWN **` which means that the static scripts are down, and I have been notified

**Comment by theedoms** [comment]
Hello Alex,
No, it still hangs on my side.
Sorry for reporting bad news :)
Do you have any other user with Free adsl access in France ? This is what I
use.
D.




*Dominique VERDEJO*
dominique.verdejo@gmail.com
mobile +33 6 08 57 92 20

14 boulevard de la République 34590 Marsillargues - FRANCE
tél +33 4 99 64 70 19 - fax: +33 9 85 92 60 14
*PERSONAL INTERACTOR <http://www.personalinteractor.net>* SIRET
42078659200030
[image: View Dominique Verdejo's profile on LinkedIn]
<http://fr.linkedin.com/in/dominiqueverdejo>

2015-06-13 19:00 GMT+02:00 Alex Hoyau <notifications@github.com>:

**Comment by theedoms** [comment]
Please note also that I have the same problem with the windows version that
I cloned and installed on my Windows 7...
I tried it with Firefox, it didn't work better.
D.




*Dominique VERDEJO*
dominique.verdejo@gmail.com
mobile +33 6 08 57 92 20

14 boulevard de la République 34590 Marsillargues - FRANCE
tél +33 4 99 64 70 19 - fax: +33 9 85 92 60 14
*PERSONAL INTERACTOR <http://www.personalinteractor.net>* SIRET
42078659200030
[image: View Dominique Verdejo's profile on LinkedIn]
<http://fr.linkedin.com/in/dominiqueverdejo>

2015-06-13 19:00 GMT+02:00 Alex Hoyau <notifications@github.com>:

**Comment by singchan** [comment]
OK, I guess other people experience that as well

Could you check the logs in the Javascript console please? (link in my
previous answer)

**Comment by theedoms** [comment]
Hello,
I just created a page from scratch with the editor then closed it and
re-opened it. That just worked fine.
Still when I try to open one of the templates I downloaded, like the one
attached, it does not work.
Can you unzip and try to open on your side ?
D.




*Dominique VERDEJO*
dominique.verdejo@gmail.com
mobile +33 6 08 57 92 20

14 boulevard de la République 34590 Marsillargues - FRANCE
tél +33 4 99 64 70 19 - fax: +33 9 85 92 60 14
*PERSONAL INTERACTOR <http://www.personalinteractor.net>* SIRET
42078659200030
[image: View Dominique Verdejo's profile on LinkedIn]
<http://fr.linkedin.com/in/dominiqueverdejo>

2015-06-14 13:53 GMT+02:00 singchan <notifications@github.com>:

> OK, I guess other people experience that as well
>
> Could you check the logs in the Javascript console please? (link in my
> previous answer)

**Comment by lexoyo** [comment]
There is no attachment :(
You have a link maybe?

**Comment by theedoms** [comment]
I am just using the template html5up-big-picture that I had attached in
zipped format.
It must have been filtered by your mailer.
D.




*Dominique VERDEJO*
dominique.verdejo@gmail.com
mobile +33 6 08 57 92 20

14 boulevard de la République 34590 Marsillargues - FRANCE
tél +33 4 99 64 70 19 - fax: +33 9 85 92 60 14
*PERSONAL INTERACTOR <http://www.personalinteractor.net>* SIRET
42078659200030
[image: View Dominique Verdejo's profile on LinkedIn]
<http://fr.linkedin.com/in/dominiqueverdejo>

2015-06-16 5:09 GMT+02:00 Alex Hoyau <notifications@github.com>:

> There is no attachment :(
> You have a link maybe?

**Comment by lexoyo** [comment]
In fact you are posting on github (by email), and github does not support attachements
Please email me at a.hoyau [at] silexlabs [dot] org
