### ISSUE TITLE
Watched the video tutorial which is written for outdated version and in French.

### ISSUE THREAD

**Issue by handy1912** [silexlabs/Silex#494]

**Comment by handy1912** [comment]
Clicked the add photo and selected in dropbox, still waiting. If it di what it is supposed to do it would be just what I am looking for.

**Comment by lexoyo** [comment]
we are currently experiencing problems with the version in production right now
what exactly is your issue?

**Comment by singchan** [comment]
everything will be back to normal in a few minutes
sorry about that

**Comment by singchan** [comment]
it is back now, please reopen the issue if you still have problems
thx

**Comment by handy1912** [comment]
Hello Alex,Today i am able to get the background image into place.The page yesterday was infinitely wide today it fits screen and is reading in the width a sensible size now althouigh this morning it was first only showing 400.I enclose a couple of screen shots. When I upload the banner as you can see it appears below the page but above the background.I then uploaded a logo which did not appear at all until I clicked allover the place and then the banner and logo came onto the page. The screenshot is with left mouse button held down. As soon as I release the mouse button they dissappear.Looking forward to having a go when current problems are sorted and hope what I am saying makes sense to you.

**Comment by handy1912** [comment]
Hello Alex,It appears to be behaving better now I can upload pics to where I wish to. Is there a handbook I can read?Thanks.

**Comment by lexoyo** [comment]
> I enclose a couple of screen shots

Github do not get the attachments by email, you can attach images when posting from the website ([here](https://github.com/silexlabs/Silex/issues/494#issuecomment-251880782))

> It appears to be behaving better now I can upload pics to where I wish to

:+1: 

> Is there a handbook I can read?Thanks.

For now there is only [the wiki here](https://github.com/silexlabs/Silex/wiki), there are some links and docs there, and you can edit it to update it when it is outdated.

If you have any questions feel free to ask here on github

I know this is not perfect, but we are all like you, users and believers in the open source way

**Comment by handy1912** [comment]
Thank you Alex,The reason I am here is that I have ditched Microsoft where I was using Open Element another French web builder and free ,open source and for the likes of me with only a little knowledge of coding a superb product. I shall read the wiki and then go back and play around until I am happy that I know how to do what I need. Mine is a very simple site, no bells and whistles just text pics and links really.Thanks but can not promise you will not hear from me again.

**Comment by handy1912** [comment]
Hello Alex,Are you still having problems?I have tried it in 3 different browsers and it does different things in each one. Chrome,Firefox and Konqueror.Maybe it is because I am usung Linux but I can not see why.Is it possible to download it to linux ?

**Comment by lexoyo** [comment]
everything should work now
I'm on linux too so it is not this
can you tell me what is your bug

**Comment by handy1912** [comment]
Start new website. Background image goes in fine every time add container works fine . Then I go to get logo png and it does not appear. If I click around randomly I can find it with mouse left down but as soon as I release mouse image dissapears. Just as before. Also I go to get my full width banner photo and it loads beneath the page but it does come onto the page if I click it and it then stays there. The screenshot with the logo on it is with me holding left mouse button down .
![2016-10-06-114707_1366x768_scrot](https://cloud.githubusercontent.com/assets/22412380/19198716/c59a2b92-8cea-11e6-83a1-5284897441ba.png)
![2016-10-06-114423_1366x768_scrot](https://cloud.githubusercontent.com/assets/22412380/19198724/d3c4257e-8cea-11e6-8bae-d80aba8b67f6.png)
![2016-10-06-114423_1366x768_scrot](https://cloud.githubusercontent.com/assets/22412380/19198744/e3895a88-8cea-11e6-9a0a-d8f78c0f9f99.png)

**Comment by handy1912** [comment]
Alex,I am sorry but for someone like me there is just not enough information to get it to work. The mobile version is a nightmare at the moment. If I could understand how to get it to work it would be the answer to all my dreams as was Open Element.The images still get put between the page and the background I can not find the bring to front button as described in some documentation I read and most of the tutorials refer to a different version ,ie user interface is not the same as mine.How do I get help? I can not understand the stuff I see on github and more often than not the questions are not actually answered.Never mind. I will continue my search.I downloaded the html to my desktop and just click that to get to the site but it is just the same as the online version.Thanks for all your help.I am actually moving to a new host and could install it there, but will it work any better?

**Comment by handy1912** [comment]
Alex, Can you tell me of a free host that has Silex on its cpanel as I really would like to use it. I can not get it to load pictures onto the page it puts them between the background and the page if I move the page out of the way  I can then drag it onto the page but this is nonsense every time you load a photo. Am I the only person having these problems. I am sorry but I can not really understand the forum questions set up.You have a brilliant product but there appears to be no effective help system for non tech type people. I can not even work out how to ask a question other than like this. The wiki was no help to me.Why are people so reluctant to have a hand book in ordinary language? Somebody who understands the system could write a hand book in less than a week. It is all very well you telling me everything is working now but your head is clearly in the sand as everything clearly is not working here. I know it is free but please do not fall into the Linux trap and think that as it is free it does not matter if you help people make it work. That is exactly the reason why Microsoft thrives.Help!

**Comment by lexoyo** [comment]
hi @handy1912 
I'll do my best to help you

> Start new website. Background image goes in fine every time add container works fine . Then I go to get logo png and it does not appear. If I click around randomly I can find it with mouse left down but as soon as I release mouse image dissapears. Just as before. Also I go to get my full width banner photo and it loads beneath the page but it does come onto the page if I click it and it then stays there. The screenshot with the logo on it is with me holding left mouse button down .

I believe you are moving the image to the background, so it goes behind the white container
I see what you are trying to do, it would be easier to add your image as a "background image" 
![screenshot from 2016-10-09 16-46-54](https://cloud.githubusercontent.com/assets/715377/19221252/05e27514-8e40-11e6-9de7-f99aae2acb82.png)
You will find the several options useful - [as this doc here says](https://github.com/silexlabs/Silex/wiki/properties)
> background image - this is another way of adding images to your site, with more control on how it is scaled
You can add your image to the container in the background (100% width) or the white one in the foreground (centered)

> Alex, Can you tell me of a free host that has Silex on its cpanel as I really would like to use it. 

You mean you want to host your instance of Silex? This is a good idea. You can use heroku for free (but will be offline a few hours a day unless you pay), or you can [get an instance at indie hosters, they are great!](https://indiehosters.net/shop/product/silex-23?category=12)

> I can not get it to load pictures onto the page it puts them between the background and the page if I move the page out of the way  I can then drag it onto the page but this is nonsense every time you load a photo

If this another issue than the one with the screenshot you gave, please open another issue in github for this and provide srceeshot

> Am I the only person having these problems. 

Last week I have pushed untested code to production by mistake, so many people have had issues. But I have fixed almost all of them and there is only one I believe, which is about z-index, so maybe the one you describe, not sure about it yet


> I am sorry but I can not really understand the forum questions set up. You have a brilliant product but there appears to be no effective help system for non tech type people. I can not even work out how to ask a question other than like this. 

Yes, I have been sai that several times, so @pierreozoux from indie hosters has offered to host a professional documentation and forums system ([like this one](https://try.discourse.org/)) for Silex. This will be online soon on help.silex.me

I am counting on you to make it a place full of questions and answers :)

> The wiki was no help to me.Why are people so reluctant to have a hand book in ordinary language? Somebody who understands the system could write a hand book in less than a week.

Well very few people have given a whole week to Silex, but sure that would be cool :)

**Comment by handy1912** [comment]
Alex,I am not moving anything anywhere. I can not find the interface where one can move imagesto the front . If Icould I would not have a problem.When I click element container it appears on the white page. When I click the element textbox it appears on the page. When I click the element add picture it goes behind the page. This is using the interface on the left not the background interface on the right as in your picture to me. That interface works fine.Where do I find the control that I have see in videos to bring a picture backwards and forwards?I was only thinking of hosting it in the hope that it would behave better under those circumstances.

**Comment by lexoyo** [comment]
> Alex,I am not moving anything anywhere. I can not find the interface where one can move imagesto the front . 
you can drag and drop it into the white container?

**Comment by handy1912** [comment]
I know I can but because it is a logo it is small and I can not see it peeping round the edge of the page. I have to move the white page out of the way to see it. Then I can drag it onto the white surface.
I can not believe you are suggesting I should do that every time I add an image. This is not what happens in the videos!!!!

**Comment by lexoyo** [comment]
i'm not sure i understand :(
for small images, you can put them on a container as a background image, with transparent background, and centered, so you can have the container "around" the image and you can manipulate it

**Comment by handy1912** [comment]
Alex,Give me step by step how to put image on page. I am not trying to do anything clever ,just put image on page.I have done as done in video be it a different version of user interface and every time the image is placed under the page not on top. I am not trying to put the image under the page that is what happens. I do not want a background image . I just want the image to be on the page and not under the page when I use the add image button on the upper left in my user interface. Why when I use the add image on the left, nothing to do with background image does the image appear under the page. It does not in the video , although I am using images already in my dropbox and in the video he is bringing a new image into dropbox. Why can I not just chose an image from my computer, dropbox has never been anything than a nightmare to me. Every other software of this type allows one to chose the image directly from the omputer and then places it in an assets file. I know nothing but it seems so strange to me.

**Comment by lexoyo** [comment]
![insert small image](https://cloud.githubusercontent.com/assets/715377/19271923/f4cdec6c-8fc6-11e6-9361-2f3012245dfd.gif)
![insert big image](https://cloud.githubusercontent.com/assets/715377/19271925/f4d5b7f8-8fc6-11e6-9e86-ca4611163568.gif)

**Comment by singchan** [comment]
Can I close this issue?

**Comment by handy1912** [comment]
Yes if you are asking me. I was neverable to get it to do what it was supposed to. I gave up and am using Zoho.


Sent using Zoho Mail






---- On Wed, 01 Mar 2017 19:55:02 +0700 singchan &lt;notifications@github.com&gt; wrote ----




Can I close this issue?
