### ISSUE TITLE
Help me test the next version of Silex

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#646]
As explained in #643 Dropbox support is broken and it is urgent to release the next version of Silex
It is a big step forward for UX thanks to Unifile and Cloud Eplorer projects which have been rewritten from scratch. Special thanks to @JbIPS, @clemos, @tariqbenezza for this.

Please test the new version on https://preprod.silex.me/ and give comments here

The following issues are already know and have to be addressed before the release. I will add your bug reports to this list. Thank you!

## critical

Silex bugs
* [x] in text editor, link dialog not visible (.modal-dialog with z-index 200)
* [x] background-repeat-y: no-repeat; bug in firefox
* [x] skill bar component does not work
* [x] after BC some templates content is duplicated and paged content is hidden (see https://github.com/silexlabs/Silex/issues/489#issuecomment-341732994)
* [x] some templates bug? e.g. the 1st one has a problem with its pages
* [x] text editor:
  * color picker bug in chrome
  * color picker do not update text in ff
  * focus when open the editor and same when close
* [x] html editor let you edit html of non-html box
* [x] possible to hide on mobile the container of sections

CE integration in Silex
* [ ] ftp sign in page not found
* [x] import, then cancel => stuck
* [x] CE error => stuck, e.g. Dashboard > import > delete folder > error > can not select nor cancel
* [x] publish
  * [x] iframe is visible for a while
  * [x] publish over another website do not work (https://github.com/silexlabs/unifile/issues/105#issuecomment-340200558)
  * [x] update publication path => preview url is not updated
  * [x] ftp errors: file exist, too many connections
  * [x] github: publish over the same image => bug (because of stream, it is important overwrite)
  * [x] github: do not copy the static js and css
  * [x] publish status dialog is sometime higher than the window and the ok button is unreachable
* [x] prod and preprod servers
* [ ] "+","image", select the image then "enter" with the keyboard, it does not select the image 
* [x] bug backward compat on Annie's site (duplicate the background container)

Still to do in CE
* [x] delete file bug in Dropbox https://github.com/silexlabs/unifile/issues/114
* [x] github multiple files upload fails: batch upload or disable multiple files upload => https://github.com/silexlabs/unifile/issues/119
* [x] session store ok? on disk? memory? in the cookie?...modal-dialog.modal-dialog.modal-dialogmodal-dialogmodal-dialog
* [x] upload error => file name stuck in file list

@fernandammoutinhobarros bugs

* [x] publication with FTP: freez the publication dialog
* [x] Image insertion from dropbox not working
* [x] Live Map doesnt show options to change adress and share buttons doesn´t show options, Skill bars, slideshow and contact form also
* [x] I can save the file, but rhe preview is empty
* [x] After publish, the result is: `{"statusCode":409,"message":"{"error_summary": "path/not_found/...", "error": {".tag": "path", "path": {".tag": "not_found"}}}"}`
* [x] Using a template: Made some changes and saved. tride to change a foto, but not working...
* [x] Well I tride ftp, but it doesn't work also. Can't make changes craches and can't preview also...
* [x] and the images don't load...
  => this is due to the preprod hosting which is a bit crappy, you should have them most of the time

@mambrus

* [x] After trying to import "editable.html" via Dropbox I get the same message as several others have already reported in #643
* [x] I'm sorry for not having followed the problem until now. Is this issue coming and going?
  => it is new, due to the old Dropbox API being droped by Dropbox

## nice to have

@Chnoe1502 
* ~make the burger menue srollable~ => no, it breakes the menu so we wait for #659 to be a component

Silex bugs
* [x] dock button disappears in docked mode 
* [ ] ERR_TOO_MANY_REDIRECTS when `SILEX_FORCE_HTTPS` is set to true
* [x] message "backward compat needs reload" when we load a site
* [x] recent files icons
* [x] FTP does not allow overwrite? [reported here](https://github.com/silexlabs/Silex/issues/646#issuecomment-341912223)

UNIFILE
* [ ] handle http code 409 (conflict) when the user creates a folder which exists
* [ ] max upload size
* [ ] use compression?
* [ ] cookie age?
* [ ] all the assets in memory during publication

**Comment by lexoyo** [comment]
I found out that the skill bar component does not work @JbIPS can you confirm?

**Comment by fernandammoutinhobarros** [comment]
I know almost nothing about code, but I can try to test ... what can I do?

**Comment by lexoyo** [comment]
Hi
Here are some ideas
* create a test website from scratch, edit some content and save on dropbox
* create a test website from a template, edit some content and save on dropbox
* edit an existing website of yours
* publish your website to a folder in dropbox
* test all the "components" (form, map, ...)

**Comment by Chnoe1502** [comment]
Hi i have tested it i can't open any html :/

**Comment by fernandammoutinhobarros** [comment]
Image insertion from dropbox not working

![image](https://user-images.githubusercontent.com/25388113/31350465-34fdf090-ad1f-11e7-9e04-17fb609b06ed.png)


Live Map doesnt show options to change adress

![image](https://user-images.githubusercontent.com/25388113/31350646-df1e3c24-ad1f-11e7-86a4-aa6ac9ab8800.png)


and share buttons  doesn´t show options

![image](https://user-images.githubusercontent.com/25388113/31350741-3bcac406-ad20-11e7-9095-d3f39191c741.png)

Skill bars, slideshow and contact form also

**Comment by fernandammoutinhobarros** [comment]
I can save the file, but rhe preview is empty

![image](https://user-images.githubusercontent.com/25388113/31350923-e8618984-ad20-11e7-82c1-367edc98912d.png)

**Comment by fernandammoutinhobarros** [comment]
After publish, the result is:

{"statusCode":409,"message":"{\"error_summary\": \"path/not_found/...\", \"error\": {\".tag\": \"path\", \"path\": {\".tag\": \"not_found\"}}}"}

![image](https://user-images.githubusercontent.com/25388113/31351145-df0e1216-ad21-11e7-91ba-8afaf093d388.png)

**Comment by fernandammoutinhobarros** [comment]
Using a template:

Made some changes and saved.
tride to change a foto, but  not working...
![image](https://user-images.githubusercontent.com/25388113/31351324-8f1d6896-ad22-11e7-8ef7-c9d933f3630b.png)

**Comment by lexoyo** [comment]
Oh not so good
Thank you all
I'll work on it and will ask you more tests after that

**Comment by mambrus** [comment]
After trying to import "editable.html" via Dropbox I get the same message as several others have already reported in #643:

![image](https://user-images.githubusercontent.com/367514/31501771-76587698-af6b-11e7-9d91-87cef4bd190a.png)

I'm sorry for not having followed the problem until now. Is this issue coming and going?

Hints for bypassing this initial hurdle greatly appreciated.

**Comment by Chnoe1502** [comment]
Please use ftp there are no problems at the moment! You only have to clear the Browser history and everything is working fine

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by fernandammoutinhobarros** [comment]
Well I tride ftp, but it doesn't work  also.
Can't make changes craches and can't preview also...

**Comment by fernandammoutinhobarros** [comment]
and the images don't load...

![image](https://user-images.githubusercontent.com/25388113/31504247-ce97e64c-af69-11e7-93b2-267e218def7d.png)

**Comment by fernandammoutinhobarros** [comment]
When i try to preview it shows the folloing error

![image](https://user-images.githubusercontent.com/25388113/31504309-f4bfa116-af69-11e7-9db3-de1ef476417c.png)

**Comment by Chnoe1502** [comment]
The images don't load because they have a new data path please put the pictures again in your webpage and for the preview i am using the path of the webpage on server directly in my Browser

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by lexoyo** [comment]
Hi

Thank you all for these useful tests

This is what I add to my list

@fernandammoutinhobarros bugs

* [ ] Image insertion from dropbox not working
* [ ] Live Map doesnt show options to change adress and share buttons doesn´t show options, Skill bars, slideshow and contact form also
* [ ] I can save the file, but rhe preview is empty
* [ ] After publish, the result is: `{"statusCode":409,"message":"{"error_summary": "path/not_found/...", "error": {".tag": "path", "path": {".tag": "not_found"}}}"}`
* [ ] Using a template: Made some changes and saved. tride to change a foto, but not working...
* [ ] Well I tride ftp, but it doesn't work also. Can't make changes craches and can't preview also...
* [ ] and the images don't load...
  => this is due to the preprod hosting which is a bit crappy, you should have them most of the time

@mambrus

* [ ] After trying to import "editable.html" via Dropbox I get the same message as several others have already reported in #643
* I'm sorry for not having followed the problem until now. Is this issue coming and going?
  => it is new, due to the old Dropbox API being droped by Dropbox

me
* [ ] message "backward compat needs reload" when we load a site

@Chnoe1502 thank you so much for finding workarounds and helping people

I do my best with the time I have

**Comment by Chnoe1502** [comment]
Here is my personal suggest for everybody who have this problems at the moment! 

1. Clear everthing from your browser history passwords, lists, auto fill in almost everthing and do this everytime if you reopen it 
2. Put your web page on your ftp filebrowser
3 put all your pictures on your ftp browser and copy it again to your webpage and everthing is working 
4 you can watch your preview if you put the path of your webpage from the server directly in the browser it doesn't matter if you use the published one or not 
5 sometime it could be you have to do the 1 step twice to load the page correctly but if it is loaded once correctly you can work on it fine i am doing my work since two weeks now and it is ok for the moment! 
6 please don't forget it is an open source project and if it is working again like the months ago it would be great again thanks to @lexoyo

**Comment by nayrangnu** [comment]
I was able to import from Github, but cannot publish to FTP. I get an error that says:

    Error message: Can't create directory: File exists


The site exists on the FTP server, created by the current live version. That version is able to publish without error. Not sure if this is a Silex error or something else.

Just found this project and am very impressed by its ease of use.

**Comment by lexoyo** [comment]
hello all 
Please **test all your issues again here: https://preprod.silex.me**
@JbIPS has worked hard so that preprod is back
thx @nayrangnu, thx @JbIPS

**Comment by fernandammoutinhobarros** [comment]
Hello! 

I was able to open the webpage created with the other version. Yes !!
Preview opens perfectly.
Saving works.
Publishing also!!

For now it seems all OK!

I have to test other things, I'll give feed back later.


THANK YOU FOR YOUR HARD WORK!!!

**Comment by lexoyo** [comment]
The FTP also?
THx

**Comment by fernandammoutinhobarros** [comment]
Only tested dropbox.

**Comment by lexoyo** [comment]
do you have a live example of a published site with ftp?

**Comment by Chnoe1502** [comment]
This is my Website

http://www.kreativbewegen.at/Winter/Winter.html

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Alex Hoyau<mailto:notifications@github.com>
Gesendet: Montag, 23. Oktober 2017 17:10
An: silexlabs/Silex<mailto:Silex@noreply.github.com>
Cc: Chnoe1502<mailto:christoph.noeckler@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [silexlabs/Silex] Help me test the next version of Silex (#646)


do you have a live example of a published site with ftp?

**Comment by lexoyo** [comment]
on the "editable" version, where is located the image `Logo_LBS_png_schwarz.jpeg` ?
can you share also the unpublished version?

**Comment by Chnoe1502** [comment]
http://www.kreativbewegen.at/WinterBearbeitung/Winter.html

It is in the Folder LOGO inside WinterBearbeitung

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Alex Hoyau<mailto:notifications@github.com>
Gesendet: Montag, 23. Oktober 2017 17:14
An: silexlabs/Silex<mailto:Silex@noreply.github.com>
Cc: Chnoe1502<mailto:christoph.noeckler@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [silexlabs/Silex] Help me test the next version of Silex (#646)


on the "editable" version, where is located the image Logo_LBS_png_schwarz.jpeg ?
can you share also the unpublished version?

**Comment by Chnoe1502** [comment]
Hi!

Today it is horrible i cannnot save and edit anything
It doesn’t matter if i use Chrome or Firefox woring on ftp

Best regards!

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Alex Hoyau<mailto:notifications@github.com>
Gesendet: Montag, 23. Oktober 2017 17:14
An: silexlabs/Silex<mailto:Silex@noreply.github.com>
Cc: Chnoe1502<mailto:christoph.noeckler@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [silexlabs/Silex] Help me test the next version of Silex (#646)


on the "editable" version, where is located the image Logo_LBS_png_schwarz.jpeg ?
can you share also the unpublished version?

**Comment by lexoyo** [comment]
Oh no :(
Are you working on preprod.silex.me? Please do, the latest version is there again as we have fixed it so it is back to normal

**Comment by Chnoe1502** [comment]
If i open it with preprod.silex.me all sections do not load except the first and the last one :/


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Alex Hoyau<mailto:notifications@github.com>
Gesendet: Dienstag, 24. Oktober 2017 19:55
An: silexlabs/Silex<mailto:Silex@noreply.github.com>
Cc: Chnoe1502<mailto:christoph.noeckler@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [silexlabs/Silex] Help me test the next version of Silex (#646)


Oh no :(
Are you working on preprod.silex.me? Please do, the latest version is there again as we have fixed it so it is back to normal

**Comment by Chnoe1502** [comment]
On opera it is working? Strange Things…

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Alex Hoyau<mailto:notifications@github.com>
Gesendet: Dienstag, 24. Oktober 2017 19:55
An: silexlabs/Silex<mailto:Silex@noreply.github.com>
Cc: Chnoe1502<mailto:christoph.noeckler@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [silexlabs/Silex] Help me test the next version of Silex (#646)


Oh no :(
Are you working on preprod.silex.me? Please do, the latest version is there again as we have fixed it so it is back to normal

**Comment by lexoyo** [comment]
> On opera it is working? Strange Things…

is it? i never tried...

> If i open it with preprod.silex.me all sections do not load except the first and the last one :/

is it still the same website?
when you click on the 1st page in the pages list on the left, does it load?

**Comment by Chnoe1502** [comment]
If i ckilck on the first page it is working and i am rather impressed that is working so smooth on opera!

Yes it is still the same page =)

One other question is it possible to make the burger menue srollable?

Thanks! =)


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Alex Hoyau<mailto:notifications@github.com>
Gesendet: Dienstag, 24. Oktober 2017 20:38
An: silexlabs/Silex<mailto:Silex@noreply.github.com>
Cc: Chnoe1502<mailto:christoph.noeckler@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [silexlabs/Silex] Help me test the next version of Silex (#646)


On opera it is working? Strange Things…

is it? i never tried...

If i open it with preprod.silex.me all sections do not load except the first and the last one :/

is it still the same website?
when you click on the 1st page in the pages list on the left, does it load?

**Comment by lexoyo** [comment]
> One other question is it possible to make the burger menue srollable? 

It should be already
Let me check

**Comment by lexoyo** [comment]
> If i ckilck on the first page it is working

could you share a zip with your website + assets by email or dropbox please? (a.hoyau [at] im-paris.fr)

**Comment by Chnoe1502** [comment]
http://www.kreativbewegen.at/Sommer/Sommer.html

On Page with mobile Version i am missing the news Page in the Burger menue

Can i send you tomorrow an Email?
Thanks

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by lexoyo** [comment]
sure

**Comment by Chnoe1502** [comment]
Wich Email adress i should use?

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by lexoyo** [comment]
> Wich Email adress i should use?

a.hoyau [at] im-paris.fr

> On Page with mobile Version i am missing the news Page in the Burger menue 

I see, it is a bug in the menu css styles
I will fix it, but in the mean time you can add this to your CSS styles
```
.silex-pages {
    overflow-x: scroll;
}
```

**Comment by lexoyo** [comment]
No wait, this will work better:
```
.silex-pages {
    overflow-y: scroll;
    overflow-x: hidden;
}
```

**Comment by Chnoe1502** [comment]
Thank you so much!!

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by lexoyo** [comment]
mit viel spass

**Comment by AndreaMonzini** [comment]
@lexoyo do you suggest to test `http://silex-editor.herokuapp.com`` or https://preprod.silex.me`?

**Comment by lexoyo** [comment]
As of now please test on https://preprod.silex.me

**Comment by parkadia** [comment]
I can log onto my website in my dropbox but unfortunately, https://preprod.silex.me suffers from other old issues. For example, it does not display page names under links making it impossible to link a container to a page. It is, therefore, unusable for anything other than minor text editing.

**Comment by lexoyo** [comment]
Hello

I do have the page names in the link dropdown list
![screenshot from 2017-10-30 16-06-59](https://user-images.githubusercontent.com/715377/32178207-76976f86-bd8c-11e7-9179-d625060aa273.png)

What is your browser
Can you help list the other bugs you have please?

**Comment by Chnoe1502** [comment]
If i want to publish in Chrome the Index file isn't created but the folders are there!

Best regards

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by parkadia** [comment]
My browser is Chrome and this is what my link dropdown list looks like:

![links_error](https://user-images.githubusercontent.com/29164121/32185404-e8779a7c-bd96-11e7-8f9d-c53cc75c7235.jpg)

I have a similar issue with the visible on list which looks like this:

![visible_on_error](https://user-images.githubusercontent.com/29164121/32185447-071a8d5e-bd97-11e7-8c1a-4d5f6b0869c6.jpg)

**Comment by lexoyo** [comment]
@chnoe1502 are you publishing to and from Dropbox?

@parkadia this happens sometimes, it will probably disappear when you refresh the browser a few times, but I add it to the list thx

**Comment by Chnoe1502** [comment]
Yes i have my editable Version and final version on dropbox. I manual save the Page as Index.html and i can publish it as a regular Version but the normal way of distribution are not really working :/

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by parkadia** [comment]
What do you mean by 'refresh'? I have used F5 ten times in succession. Each time, I have had to reload the website and each time the problem does not disappear.

I first noticed this issue when you recommended using preprod.silex.me back in June.

I have never experienced this issue in editor.silex.me.

I appreciate that preprod.silex.me has been reconstructed recently BUT it is not EXACTLY the same as it was in June because it has a new procedure for accessing the dropbox.

Why do you not just add this procedure to editor.silex.me?

**Comment by bialyjerozy** [comment]
Hey, i'm getting madness because of this... i've tried http://silex-editor.herokuapp.com`` and https://preprod.silex.me, in none of them i can't make any of my images work.. i tried to put new images from dropbox, it seems like it still got some bad patch, after about 6 hours and 2 nights i'm giving up.. :/ I can't make any changes in site because of this.. could anyone help me?

**Comment by lexoyo** [comment]
> What do you mean by 'refresh'? I have used F5 ten times in succession. Each time, I have had to reload the website and each time the problem does not disappear.

oh ok :(
then could you please open the [developer console in chrome](https://developers.google.com/web/tools/chrome-devtools/console/) and screenshot what it says in the "console" tab please?

> I first noticed this issue when you recommended using preprod.silex.me back in June.
> I have never experienced this issue in editor.silex.me.
> I appreciate that preprod.silex.me has been reconstructed recently BUT it is not EXACTLY the same as it was in June because it has a new procedure for accessing the dropbox.
> Why do you not just add this procedure to editor.silex.me?

Because we had to create the file explorer from scratch, and the integration in Silex was a huge change. The work with @JbIPS and @clemos and @tariqbenezza began more than a year ago

See these changes here:
* [the new unifile v1.0.0](https://github.com/silexlabs/unifile/pull/71) - began 1 year an half ago (march 15)
* [the new cloud explorer 2](https://github.com/silexlabs/CloudExplorer2/) - began 1 year ago (july 7)
* [integration of the new cloud explorer into Silex](https://framagit.org/silexlabs/Silex/merge_requests/13) - began 5 months ago

**Comment by lexoyo** [comment]
> some templates bug? e.g. the 1st one has a problem with its pages

Could someone help me test all the templates? Open, change things, save, publish, check the mobile version...

**Comment by bialyjerozy** [comment]
Lexoyo could you help me with my issue please?

**Comment by lexoyo** [comment]
> Lexoyo could you help me with my issue please?

Oops sorry I did not see your message, thank you for notifying me

> Hey, i'm getting madness because of this... i've tried http://silex-editor.herokuapp.com`` and https://preprod.silex.me, in none of them i can't make any of my images work.. i tried to put new images from dropbox, it seems like it still got some bad patch, after about 6 hours and 2 nights i'm giving up.. :/ I can't make any changes in site because of this.. On the preview, everything seems bo be allright, but after im trying to save/publish, theres no images in assets folder, even when i put them there manually,, there's no images at all. Is there anyone who could help me with this?

On preprod.silex.me, you can authorize dropbox and access your dropbox files, then when you click on an image what does it do?

**Comment by bialyjerozy** [comment]
It loads image to the template, i can move, resize etc it.

**Comment by lexoyo** [comment]
oh ok, so what is the bug exactly?

**Comment by bialyjerozy** [comment]
It seems like it can't save them, after im trying to save/publish, there's no images in assets folder. In preview everything seems fine, but when i'm trying to upload published site to ftp, every single image is broken like here: https://user-images.githubusercontent.com/25388113/31504247-ce97e64c-af69-11e7-93b2-267e218def7d.png
Even when i put them into folder assets there manually, there's no images at all.

**Comment by lexoyo** [comment]
oh
can you share the site you put on the ftp please?

**Comment by bialyjerozy** [comment]
sure: www.fotofun.pro, but now i't old version of the site, should i upload new corrupted one?

**Comment by bialyjerozy** [comment]
or do You mean files?

**Comment by lexoyo** [comment]
yes please upload the corrupted one somewhere

**Comment by bialyjerozy** [comment]
done, on the same address

**Comment by lexoyo** [comment]
this is not the published site, but the editable version. can you publish your site to a folder and then upload it or publish directly to FTP?

**Comment by bialyjerozy** [comment]
What do You mean? Last time i edited this site was loong time ago, i could not remember how it was done, but now, when i click publish i got created 3 new folders- assets, css and js, without any html file, so i save site as, and got editable.html file and then i just change name to index.html, am i wrong?

**Comment by lexoyo** [comment]
When you publish it is supposed to create index.html
Your editable.html references images with a relative path to your cloud storage, so this can not work
When you publish:
* does it end with a message like "success" + a link to the published website?
* where is the editable.html file, dropbox?
* where do you publish to, ftp?

**Comment by AndreaMonzini** [comment]
Hello, i'm testing the `https://preprod.silex.me/` and i have problems with the "Galaxee" template.
I cannot see menu and other elements:
Firefox 56.0.2, FTP access.

![screen shot 2017-11-03 at 3 54 50 pm](https://user-images.githubusercontent.com/12413409/32380661-e594a012-c0b0-11e7-8ebe-779540506063.png)

**Comment by lexoyo** [comment]
Nice one, thank you andrea
I add it to the list and will get back to you soon
(Also reported here https://github.com/silexlabs/Silex/issues/489#issuecomment-341732994)

**Comment by bialyjerozy** [comment]
Something changed, 2 days ago i could save it without any error now i got this message: 
 "I did not manage to publish the website. You may want to check the publication settings and your internet connection
Error message: Unknown error from dropbox" It seems like error with privileges?

- Before that i could publish it with a link to published site, but when i clicked link there was some kind of error with test string
- Editable file is on dropbox
- I'm publishing it to dropbox, then copying this to ftp

**Comment by lexoyo** [comment]
Ok @bialyjerozy very interesting
Let me push some changes I have made yesterday and test again. I'll do that tonight

**Comment by bialyjerozy** [comment]
Okay, let me know when i should try again, oh and one more, maybe i should have buissness dropbox account instead of personal? I wonder if theres an option to force preprod.silex to ask about dropbox permission, like it was in normal silex editor.

**Comment by lexoyo** [comment]
> Edit. i think i know what could be the problem with saving, in dropbox settings, in connected applications i got only silex-editor.herokuapp.com application, not preprod one, but i dont know how i could add this manually

you are right, it is a different app, but this should work nonetheless 

> maybe i should have buissness dropbox account instead of personal? I wonder if theres an option to force preprod.silex to ask about dropbox permission, like it was in normal silex editor.

no it is fine with personal, I believe that this bug is fixed on my local computer, I tell you when I will have pushed the fix on preprod.silex.me

**Comment by lexoyo** [comment]
This is live on https://preprod.silex.me
@bialyjerozy could you try to publish again
* from dropbox to dropbox and then upload to FTP
* from dropbox to FTP directly

**Comment by bialyjerozy** [comment]
Same error when trying to publish to dropbox, but when trying to publish on ftp, it saved folders, some pictures and then got error message: exceeded number of connections per user... :/

**Comment by AndreaMonzini** [comment]
Sometimes i'm unable to see files, only directories when i try to load in FTP the Galaxee template:
![screen shot 2017-11-03 at 6 56 03 pm](https://user-images.githubusercontent.com/12413409/32389241-751fcd24-c0ca-11e7-8c69-b343729d61f7.png)
While i receive error message when i try to publish (to FTP)
![screen shot 2017-11-03 at 7 08 00 pm](https://user-images.githubusercontent.com/12413409/32389410-d5d095fe-c0ca-11e7-8b24-5ea1850bb413.png)

Firefox 56, File managed with FTP.

**Comment by bialyjerozy** [comment]
I tried creating new page and then publish it in dropbox, same error, i even tried on new dropbox business account, different browsers, still same error
![z](https://user-images.githubusercontent.com/33108613/32400775-c061418e-c104-11e7-8c81-9ec66a7beaa7.JPG)

 on http://silex-editor.herokuapp.com/ i got error too, but different:
![z](https://user-images.githubusercontent.com/33108613/32400746-5662a71e-c104-11e7-86c0-01a63d4643bc.JPG)

**Comment by lexoyo** [comment]
Ok guys, thank you for your reports, I'll investigate and will get back to you

**Comment by lexoyo** [comment]
@parkadia could you test again and tell me what is written in the javascript console please?

**Comment by lexoyo** [comment]
@AndreaMonzini concerning the galaxee template, could you give it a try again on preprod, I fixed an issue which was reloading the template after the 1st try to open it ([this particular code change](https://github.com/silexlabs/Silex/commit/cc2b70e3de5902d9750522baf8b259cc34ba9666#diff-4c3a6cc936c7ffbf2237f1dff6849c99))

**Comment by bialyjerozy** [comment]
Alex, are you going to check and try to fix problem with publishing sites or it is impossible?

**Comment by lexoyo** [comment]
Yes I am working on it with @jbips

**Comment by lexoyo** [comment]
Some things that could help
* open the developper console and tell us what errors you have in the console tab (see the link to a tutorial I shared a few days ago)
* what is your browser?
* could you share your editable site on Dropbox with me ? a.hoyau at im-paris.com

**Comment by parkadia** [comment]
I did not use the developer console because my issue with the 'link' and 'visible on' menus appeared to be fixed. I added a new page, successfully loaded images and linked to the new page.

However, when I came to publish preprod.silex said no publish directory was selected. I configured this but now I am experiencing the same publishing problems as @bialyjerozy and get the same error message above. I have repeatedly checked the publication settings and my internet connection and all seem OK.

I am using dropbox because I cannot get ftp to work. The dialogue box says that my access details are invalid but I can log on to the ftp server using WinSCP.

**Comment by lexoyo** [comment]
> I did not use the developer console because my issue with the 'link' and 'visible on' menus appeared to be fixed. I added a new page, successfully loaded images and linked to the new page.

ok, this comes and goes :(
if you see it again please open the dev console

> However, when I came to publish preprod.silex said no publish directory was selected. I configured this but now I am experiencing the same publishing problems as @bialyjerozy and get the same error message above. I have repeatedly checked the publication settings and my internet connection and all seem OK.

ok, i'll check thx

> I am using dropbox because I cannot get ftp to work. The dialogue box says that my access details are invalid but I can log on to the ftp server using WinSCP.

winscp is ssh right? maybe you should try SFTP

**Comment by lexoyo** [comment]
Oh and please everybody, empty your cache when you start a new test session

**Comment by AndreaMonzini** [comment]
@lexoyo i retested Galaxee with `https://preprod.silex.me/` template and now the menu  and other element are visible !
I have problem with publishing to FTP, the workaround is to create a new publishing folder for every time i need to publish ( it doesn't work if i just delete manually files inside the publishing folder )

![screen shot 2017-11-04 at 5 42 41 pm](https://user-images.githubusercontent.com/12413409/32407417-d81ee608-c188-11e7-879b-befe0252f2b2.png)

**Comment by AndreaMonzini** [comment]
Now i'm blocked for an unknown error when i try to access to FTP

![screen shot 2017-11-04 at 6 01 26 pm](https://user-images.githubusercontent.com/12413409/32407557-19daeb58-c18b-11e7-9e52-9b7689387da9.png)

**Comment by lexoyo** [comment]
> @lexoyo i retested Galaxee with https://preprod.silex.me/ template and now the menu and other element are visible !

Ok, we are moving forward! 👍 

> I have problem with publishing to FTP, the workaround is to create a new publishing folder for every time i need to publish ( it doesn't work if i just delete manually files inside the publishing folder )

Good catch, thx, I'll use it to debug 

> Now i'm blocked for an unknown error when i try to access to FTP

:-( 
can you try again later and let me know if it was temporary?

**Comment by AndreaMonzini** [comment]
Now i see only folders, not files like editable.html

I tried to delete cache and reload.

![screen shot 2017-11-04 at 6 19 18 pm](https://user-images.githubusercontent.com/12413409/32407693-e07b4ee6-c18c-11e7-9db7-f056de4bc3cd.png)

**Comment by lexoyo** [comment]
> Now i see only folders, not files like editable.html

the files may be hidden if you are asked to select a folder

**Comment by lexoyo** [comment]
use the file explorer button:
![screenshot from 2017-11-04 18-22-23](https://user-images.githubusercontent.com/715377/32407704-2348fe26-c18d-11e7-9b82-8379a2ccf1f6.png)

**Comment by AndreaMonzini** [comment]
Ok, used file explorer and files reappeared, then i went to Dashboard to import website and now files are visible! But when i use Dashboard i do not see the option to selected folders only.

**Comment by bialyjerozy** [comment]
> open the developper console and tell us what errors you have in the console tab (see the link to a tutorial I shared a few days ago)
what is your browser?
could you share your editable site on Dropbox with me ? a.hoyau at im-paris.com

Should i open console on editor, editable version or index.html?
I've tried all browsers, now i'm working on chrome.
I've just shared You editable file via e-mail.

**Comment by lexoyo** [comment]
Hello

I have worked on the new version today and I tried to address these issues
*  the publication should work better on FTP (too many clients issue)
* the publication on dropbox and github is still broken but I think that the problem is now only in unifile and @JbIPS will probably help me with this
* color picker issues and text editor issues
* @parkadia and @MarcelloCavallo issues with pages and links should be fixed too

I would be very grateful if you could give it a go again and test everything but the publication on github and dropbox again. 
http://preprod.silex.me/

It may be good now to open a new issue for each bug, just remind me that you tested on preprod.silex.me

Thank you

**Comment by lexoyo** [comment]
Ok thank you @fernandammoutinhobarros 
You can do more tests on the edition if you have time
@JbIPS and me are working on the publication, it will work soon

**Comment by fernandammoutinhobarros** [comment]
ok thanks

**Comment by lexoyo** [comment]
what i did yesterday and today
* html editor let you edit html of non-html box
* fixed dock button disappears in docked mode 
* fixed dropbox logo do not show up in recent files icons anymore
* fixed "it should not be possible to 'hide on mobile' the container of a section"

and @JbIPS is working on uploads and github and dropbox and ftp issues (poor him ;) )

**Comment by lexoyo** [comment]
Hello
Has someone tested the SFTP for save, load and publish?

**Comment by MarcelloCavallo** [comment]
J'essaye ce soir, bonsoir Marcello .

**Comment by parkadia** [comment]
I did try but I could not log on. However, I am told this is probably 
our issue - permissions / security etc.

As I cannot log on with FTP either, I am limited to dropbox. I can edit 
but I cannot publish.

Stella

**Comment by singchan** [comment]
OK thx
-- 
Alex Hoyau
+33(0)676683806
Skype: alex.hoyau

**Comment by lexoyo** [comment]
preprod is back
I hope everything will work fine
I already know that publish with dropbox does not work
Could you test everything else? (save, load, publish with ftp and github, ...)
Thank you for your help, we are almost there, one last session of debug before a release

**Comment by arasexyz** [comment]
Hi ! 
i'm trying to connect from the FTP way at https://preprod.silex.me, in the settings (3 gears wheels) >publish settings > service ftp> configure>ftp > OK 

and i'm back on the publish settings. 

if i do it again, it 's looping.

By the dashboard way , if i'm trying to import website, it's give me a : "Not Found" blanck page....

thanx 4 your Job , it's a good project !

**Comment by lexoyo** [comment]
Good catch! Thx @arasexyz

**Comment by arasexyz** [comment]
Hello, 
Listen, i'm supposed to do (in 4 days )a formation(8 persons) to learn how to administrate a small website .
i've tryed https://preprod.silex.me (ftp not working)to avoid difficulty with https://editor.silex.me (impossible to reopen an existant project with ftp(working)) 
What could i do to go on use this wonderfull project ? 
thank you

**Comment by arasexyz** [comment]
![ouvrir-_precedent](https://user-images.githubusercontent.com/33373062/33479480-94a62caa-d68d-11e7-8941-defc1ac10b19.png)
that is the error given by the  https://editor.silex.me way trying to open last website session.
What should i do ?

**Comment by lexoyo** [comment]
> that is the error given by the https://editor.silex.me way trying to open last website session.
> What should i do ?

Please share the HTML page with me

**Comment by lexoyo** [comment]
> What could i do to go on use this wonderfull project ?

If you can use another service than Dropbox please use editor.silex.me

**Comment by arasexyz** [comment]
[ftp_01122017.zip](https://github.com/silexlabs/Silex/files/1521480/ftp_01122017.zip)

here is the "www" content

i prefer use the FTP way if it's working

thank you for the help

**Comment by lexoyo** [comment]
> i prefer use the FTP way if it's working

It should work on editor.silex.me 
And I need testers for that on preprod but it should work there too

> that is the error given by the https://editor.silex.me way trying to open last website session.
> What should i do ?

I tried and it works well
![screenshot from 2017-12-03 00-30-42](https://user-images.githubusercontent.com/715377/33520744-3fe9a090-d7c1-11e7-8af4-680867688354.png)

Could you try again plz?

**Comment by arasexyz** [comment]
Hi ! it's seems to works perfectly by the "editor.silex.me" way, i will use this to do my small formation.
thanks for the test !

**Comment by arasexyz** [comment]
I've got this error message when i want to publish after saving with editor.silex.me..
![unknown service](https://user-images.githubusercontent.com/33373062/33728782-db6b4ccc-db7b-11e7-908d-35847a238b05.png)

**Comment by arasexyz** [comment]
when i clic on the link , i obtain this :
![cannot get](https://user-images.githubusercontent.com/33373062/33728906-50250e72-db7c-11e7-9f7b-a1f28ada56a1.png)

**Comment by arasexyz** [comment]
It's solved by re-putting the ftp folder with the publish settings

**Comment by lexoyo** [comment]
Hello
We have worked hard with @JbIPS and everything seems ready: all the problems in the list have been fixed
Could you @all give it a go again, on https://preprod.silex.me ?
Then we will release it on editor.silex.me
Very last test hopefully, please help! :)

**Comment by JbIPS** [comment]
Thank you all for your patience, hope you will like this new version!

**Comment by lexoyo** [comment]
I made [this template](http://lexoyo.me/GrrHost/26292/transitive/editable.html) and https://preprod.silex.me seems to work well

only problem: the publication on github gives me:
```
An error has occurred.

I did not manage to publish the website. You may want to check the publishing settings and your Internet connection.

Error Message: Can not Change Tree: Server Error
```
can someone help me test https://preprod.silex.me ? you can [clone my template here](https://github.com/singchan/silex-templates/tree/transitive) and try to publish it. or simply try to publish any site on github and dropbox

**Comment by fernandammoutinhobarros** [comment]
Hi,

Just tried to upload a file on prepod and it's not working... it only
gives-me  a blank screen.



[image: Imagem intercalada 1]


Melhores cumprimentos,



*Fernanda Moutinho Barros *

*CONSULPAV* *Consultores e Projectistas de Pavimentos, Lda.*

Rua da Zona Industrial, N.º 6 A, Casais da Serra

2665-305 Milharado – Mafra – Portugal
Telef.: (+351) 219 757 003 <+351%2021%20975%207003>        Fax: (+351) 219
757 014 <+351%2021%20975%207014>

www.consulpav.com     www.facebook.com/consulpav




...

2018-01-07 19:50 GMT+00:00 Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
Oh my 🌴 !
The build failed or something, I will deploy again now, and see if it works
Sorry about that, my bad

**Comment by fernandammoutinhobarros** [comment]
Hi again,

Sorry, still does not working... 😢

thanks for all the hard work.


Melhores cumprimentos,



*Fernanda Moutinho Barros *

*CONSULPAV* *Consultores e Projectistas de Pavimentos, Lda.*

Rua da Zona Industrial, N.º 6 A, Casais da Serra

2665-305 Milharado – Mafra – Portugal
Telef.: (+351) 219 757 003        Fax: (+351) 219 757 014

www.consulpav.com     www.facebook.com/consulpav




...

2018-01-09 22:06 GMT+00:00 Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
Sorry about that, I should have tested after deploying
You can test now

**Comment by fernandammoutinhobarros** [comment]
Hi again,

So now it works, but publish is not working, I use dropbox... the popup
window stays like this and does nothing....


Just editing and previewing works fine.


;(


Thanks for the help.

[image: Imagem intercalada 1]







*Fernanda Moutinho Barros *

**Comment by lexoyo** [comment]
Fernanda
You need to go here to post images
https://github.com/silexlabs/Silex/issues/646#issuecomment-356957719

**Comment by fernandammoutinhobarros** [comment]
Hi Lexoyo,


The window that shows just says
"I am about to publish your site. This may take several minutes."  "Close"

And it stays like that forever... 

![image](https://user-images.githubusercontent.com/25388113/34833305-062571c8-f6e7-11e7-82f7-76edeb2cb40a.png)

**Comment by lexoyo** [comment]
Here is a bug I have on https://preprod.silex.me in firefox only
Does someone else have this bug? I can not reproduce on my local computer nor in chrome...

**Comment by lexoyo** [comment]
And the bug here :
![screencast](https://user-images.githubusercontent.com/715377/34919549-0a3e28dc-f966-11e7-9676-c426c340cc49.gif)

**Comment by lexoyo** [comment]
@fernandammoutinhobarros I can not reproduce... Can you test again? Maybe test with github too? And maybe share your website with me on dropbox (a.hoyau [at] im-paris.fr)

**Comment by fernandammoutinhobarros** [comment]
Hi Lexoyo,

I've shared with you my files.


Tested your bug in mozzilla and it's the same for me.

**Comment by IOU4something** [comment]
Cant seem to be able to publish to dropbox or to ftp. I get message "553 Can't open that file: No such file or directory" in both cases.

**Comment by lexoyo** [comment]
Does the publication path exist?

**Comment by fernandammoutinhobarros** [comment]
Hi Alex, 
I still have that problem to. Publish fails....

![image](https://user-images.githubusercontent.com/25388113/35157556-4033d06c-fd2c-11e7-88ba-34ea96f83648.png)

![image](https://user-images.githubusercontent.com/25388113/35157522-26029d86-fd2c-11e7-827f-c5f227180d79.png)

**Comment by fernandammoutinhobarros** [comment]
Ok.

So I tested creating a new webpage from a blank page, and it publishing works...
I think I have to rebuild the hole webpage :(

**Comment by lexoyo** [comment]
I'm trying to fix the publication issues
If you find what is the difference between the one which works and the old one, this would help

**Comment by lexoyo** [comment]
@fernandammoutinhobarros it looks like something in the page "venue" makes it fail with the error message `InvalidCharacterError: String contains an invalid character`

I made a copy of your site, then deleted the pages one by one and tried to publish. Can you do that with the elements on this page and tell me what element does that? It will help me a lot

Thank you!

**Comment by fernandammoutinhobarros** [comment]
@lexoyo 
Thank you for the help, I will try to do that.

**Comment by leifk** [comment]
@lexoyo 
I am trying to update a website I created on https://editor.silex.me/, loading from Dropbox. I found this thread, which directed me to open in https://preprod.silex.me/. 

I did so but cannot see any of the content from my original site, except the title. Everything appears blank, even when I preview the site. Any idea whats going on? 

Thanks!

**Comment by lexoyo** [comment]
Hi
Can you try to click on a page to see if it makes the content appear please?

**Comment by lexoyo** [comment]
I saw @leifk bug once today but then I refresh and impossible to reproduce it again. If one can reproduce it please share

Otherwise I believe there is only 1 important bug left: the publication to github which is about to be resolved by @JbIPS who found where it comes from 

So I will start the release of preprod to editor.silex.me very soon. It represents 2 years of work on our free time, so this is kind of emotional ;)

A last test someone? Last bug reports before we release?

**Comment by fernandammoutinhobarros** [comment]
@lexoyo
Hi, so I finally had the time for this.
I erased the sub-page that has the problem. 
Created again, the error continued, so I changed the subpage name.
Now I'm painfully adding element by element and publishing after each add... :S ... its' a patient task
It seems to go wrong when:
- Elements are overlapping - had an image on a bit over a text box (I have the same overlaping on another page and 
- Elements in container - had some with groups of images and text inside to keep them allways together
- Text with links...


just added a text box and published it was fine, added a link to a word on text and publish error
![image](https://user-images.githubusercontent.com/25388113/36909808-fcd717bc-1e36-11e8-8b11-20d272a39c9f.png)


I'll keep trying :D

**Comment by fernandammoutinhobarros** [comment]
Ok so tried to publish again after giving error 2 times, on the 3rd time it worked.
I didn't change anything... :s

**Comment by fernandammoutinhobarros** [comment]
After adding some more text elements 

![image](https://user-images.githubusercontent.com/25388113/36911210-bf295fe8-1e3a-11e8-94cd-7abae29937d2.png)

**Comment by fernandammoutinhobarros** [comment]
![image](https://user-images.githubusercontent.com/25388113/36916195-1c552d68-1e4b-11e8-86bc-b604aa7b8ecb.png)

**Comment by fernandammoutinhobarros** [comment]
It's not saving again. 
what browser is best for silex?
maybe chrome is the problem?

**Comment by fernandammoutinhobarros** [comment]
Is prepod working? 
I can save, but publish isn't working.
I'm rebuilding the website...

**Comment by lexoyo** [comment]
> what browser is best for silex?

Chrome and Firefox work the same for silex


> Is prepod working?
> I can save, but publish isn't working.

It works but publish has issues
@JbIPS fixed the problem but it is not live yet. It will be next week

> I'm rebuilding the website...

So sorry :-/

**Comment by fernandammoutinhobarros** [comment]
Ok.
I made it again, now it's working.
Publish has problems, I  had to repeat publish  several times, but it worked.

Thanks this is a very good tool! 
Keep on the excellent work!
 :)

**Comment by lexoyo** [comment]
Quick update: we tried to release yesterday night but there are still issues sometimes with publication. Working on it with @JbIPS

**Comment by lexoyo** [comment]
Final chance to test this "new" version
@JbIPS finally managed to fix the last known bug
I am running some tests before I publish on editor.silex.me, I would love some help (please test a template, then publish somewhere using one of the service)

**Comment by fernandammoutinhobarros** [comment]
I still have issues on publication, I have to repeat it several times until the publish is successful.

**Comment by JbIPS** [comment]
I tried a random template (Startup) and the backward compatibility failed:
```
TypeError: e is null                         admin.js:495:148
av               https://preprod.silex.me/js/admin.js:495:148
Zt/</</</</<      https://preprod.silex.me/js/admin.js:488:91
$u               https://preprod.silex.me/js/admin.js:496:418
Zt/</</</<        https://preprod.silex.me/js/admin.js:488:75
Zu                https://preprod.silex.me/js/admin.js:498:58
Zt/</</<          https://preprod.silex.me/js/admin.js:488:55
Yu               https://preprod.silex.me/js/admin.js:498:171
Zt/</<            https://preprod.silex.me/js/admin.js:488:37
Xu               https://preprod.silex.me/js/admin.js:499:494
Zt/<              https://preprod.silex.me/js/admin.js:488:19
Wu               https://preprod.silex.me/js/admin.js:503:244
Zt                 https://preprod.silex.me/js/admin.js:488:1
Wt/<             https://preprod.silex.me/js/admin.js:445:174
ru/f<            https://preprod.silex.me/js/admin.js:466:112
<anonyme>                                  self-hosted:991:17
```

**Comment by lexoyo** [comment]
@fernandammoutinhobarros is it with the site you shared with me on dropbox?
@JbIPS I don't see this template anywhere :-/
I'm releasing now

**Comment by fernandammoutinhobarros** [comment]
@lexoyo 
Hi, I rebuild it with the new version of silex, so it's a new file.
I gives-me the error, but I repeat publish until it works :P

**Comment by FranGamer1892** [comment]
I've spotted some bugs on #761
