### ISSUE TITLE
Feature request: new text editor

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#662]
The current text editor is bad: it has bugs (select text, change color, sometimes it changes the whole line) and lacks (insertion of images, css styles which can be customized in Silex CSS editor...) and it creates bad HTML markup

Here are some better text editors, we should choose one which has a GPL license a replace the current text editor
* https://draftjs.org/
* http://getcontenttools.com/demo
* https://www.froala.com/wysiwyg-editor/inline
* https://wymeditor.github.io/wymeditor/dist/examples/22-custom-styles.html (avec styles custom possibles)
* https://imperavi.com/redactor/
* http://summernote.org/examples/

Help wanted on this, I will not be able to do it and then maintain it, so this is a good way to become a contributor. I can help you do it and guide you...

**Comment by ribrdb** [comment]
Actually the closure editor is pretty sweet once you learn how to customize it. You can easily support images, custom css, or cleaned up html by writing plugins. The documentation isn't great, but the [Closure book](https://www.safaribooksonline.com/library/view/closure-the-definitive/9781449381882/ch09.html) is helpful.
Are you aware of [ContentEditableField](https://google.github.io/closure-library/api/goog.editor.ContentEditableField.html)? I think it's a better fit for this type of interface - it's supported in modern browsers and lets you edit right in place. goog.editor.Field is more for something like gmail where you explicitly want to isolate yourself from the css of the current document.

**Comment by lexoyo** [comment]
This is really interesting, thx

I have several questions in mind:

1. Are you saying that we could use contentEditable with closure editor? We would keep the same ui?
2. Would it make the markup better? Would it solve the selections issues?
3. Are you willing to help with guidance or code?

Thank you so much for the links. I have integrated this editor 5 years ago and I had little time to do it and no knowledge of closure components

**Comment by ribrdb** [comment]
1.  Yes closure editor supports contentEditable. For example, when you click the edit button you can make the currently selected div editable in place. 
Something like:
```javascript
if (!element.id) {
  element.id = goog.string.createUniqueString();
}
const editor = new goog.editor.ContentEditableField(element.id);
// register plugins, maybe show toolbar over element, etc.
editor.makeEditable();
goog.events.listen(element, "blur", ()=>{editor.makeUneditable(); editor.dispose() });
```
Actually you probably need to be smarter about when to make it uneditable, since clicking a toolbar button will at least temporarily loose focus, or opening a link dialog, etc.
You could even make the whole page editable, but that's much harder to manage. 
2.  This doesn't change the markup, but that's not hard to do. You can extend or replace the BasicTextFormatter to change how it styles text, and/or write plugins to cleanup the markup after it's edited. All you need to do is implement the cleanContentsDom and/or cleanContentsHtml methods of goog.editor.Plugin.
I don't know about the selection issues. Do you have a reproducible test case for that? Does it happen in all browsers?
3.  I don't know how much time I've got but I can try to help.

**Comment by lexoyo** [comment]
> 2. This doesn't change the markup, but that's not hard to do. You can extend or replace the BasicTextFormatter to change how it styles text, and/or write plugins to cleanup the markup after it's edited. All you need to do is implement the cleanContentsDom and/or cleanContentsHtml methods of goog.editor.Plugin.

This is what we really need to address I guess

> I don't know about the selection issues. Do you have a reproducible test case for that? Does it happen in all browsers?

I changed the behavior a bit and I believe it is acceptable now

**Comment by lexoyo** [comment]
>> I don't know about the selection issues. Do you have a reproducible test case for that? Does it happen in all browsers?

> I changed the behavior a bit and I believe it is acceptable now

I correct myself: more tests reveal that there are still selection issues. Sometimes I select a few words and change the color, but the color is applied to the whole line

This is something we really need to fix, as much as the "not standard" markup...

**Comment by lexoyo** [comment]
I have found this editor which supports inline mode and looks good
https://www.froala.com/wysiwyg-editor

Inline editing is what was suggested in #52

**Comment by JbIPS** [comment]
Worth a try. I love the way JS lib **still** requires JQuery...

**Comment by lexoyo** [comment]
Froala is not open source :(


I found this to build the text editor from scratch
https://github.com/timdown/rangy/wiki

And this open source text editor from the list is cool

http://getcontenttools.com/demo

**Comment by budislav** [comment]
Yes!
Inline editor is urgently needed.
Froala is really good inspiration.
Maybe some open source text editor like Brackets can be useful?

**Comment by lexoyo** [comment]
@budislav I'm looking into this right now
wysihtml5 is not supported anymore and they recommend http://wysihtml.com/

**Comment by budislav** [comment]
@lexoyo even better :)

**Comment by lexoyo** [comment]
So, I did some tests and it should be "quick" to do, here is what I plan

* [ ] check the UX with you guys
* [ ] basic UX and inline editing, more UX tests
* [ ] basic toolbar
* [ ] links, with `target` options
* [ ] links with Silex pages as options - this one is tricky since there is already the option in the properties (cc @budislav)
* [ ] add image handling
* [ ] nice to have if I am patient enough: HTML/code view, tables

**Comment by lexoyo** [comment]
cc @JbIPS @budislav @clemos @ondrejec @SouroucheB @TheCause @jennparker @tariqbenezza @camcrock @zabojad @pierreozoux

**Comment by budislav** [comment]
@lexoyo sorry for delay. 
So I really think we need to make this like webflow work flow. I will show you how that should be. I think ul, ol, img and other html elements should be added like a separate elements, that would allow user much more flexibility and options.

1. On the very beginning you have to choose what do you want to insert, you have:
- heading (html element)
- paragraph (html element)
- text link (html element)
- text block (silex have this, awesome!)
- block quote (div, modified)
- rich text (div, combination of html elements)
So for now headings, paragraph, text link and text block are what I think we must have.
![screenshot from 2018-08-03 19-20-05](https://user-images.githubusercontent.com/3619927/43656741-ca11ebae-9753-11e8-94ea-228ff6eaed52.png)

2. User choose for example to add text block in one empty container which can be added also but that is not important for now.
![screenshot from 2018-08-03 19-32-10](https://user-images.githubusercontent.com/3619927/43656794-03822f34-9754-11e8-8bcf-7c7bc596c137.png)
So when user add it style settings should be opened. When he double click o text  box also.
Now if he want to change some text on fly he need to double click on word to select word or letters so options for editing will show on canvas like this
![screenshot from 2018-08-03 19-35-12](https://user-images.githubusercontent.com/3619927/43656912-7222cc6e-9754-11e8-82b4-3445ed95399f.png)
And there are enough options for this fast text editing, everything we need there: bold, italic, insert link, wrap with span, and clear formating.
On the element settigns tab there is nothing particular for this element because it is not really htmls element it is div with text right.
![screenshot from 2018-08-03 19-37-30](https://user-images.githubusercontent.com/3619927/43657007-bfc1434c-9754-11e8-9fcf-72090d335162.png)
but if user now choose to insert heading element this is how it should look like
![screenshot from 2018-08-03 19-38-27](https://user-images.githubusercontent.com/3619927/43657019-d4f2f742-9754-11e8-95a4-8997eea7a904.png)
and every time user can access to these options fast by clicking on that small settings button , or on element settings tab. But he can also change same options when double click on word or letters.
![screenshot from 2018-08-03 19-50-44](https://user-images.githubusercontent.com/3619927/43657607-9c9720a6-9756-11e8-993a-b988201829b3.png)
And also like for the each element he can switch to style tab.

**Comment by lexoyo** [comment]
I see, thank you @budislav very interesting discussion!

Since Silex has no "positioned" mode, only "absolute", it is not possible for now to have separate elements for heading, link, ... We can only have a rich text for now. How does webflow rich text behave?

**Comment by budislav** [comment]
I  know we need css grid desperately, actually webflow team just sent an email they are working on css grid, it will be finished this month:
"We’re nearing the end of our development cycle on a grid layout system in Webflow that is powered by CSS grid. In short, grid in Webflow will introduce an entirely new way to build layouts — the largest change to the styles panel since our introduction of flexbox in April of 2016. One particularly exciting note here is that grid will feature on-canvas controls for positioning grid items, setting rows and columns, and for defining grid areas on your layouts, so you’ll be able to work directly with your grid layouts on the Designer canvas. "
Soooo, we need to see how that will work.
Richtext is just a div with headings and paragraph.

![screenshot from 2018-08-04 03-23-21](https://user-images.githubusercontent.com/3619927/43671188-cc33e5a8-9795-11e8-892c-62ddbdc94b58.png)

**Comment by lexoyo** [comment]
Thank you @budislav for all this technology watch! As usual you have all the latest info. Very logical choice for webflow... We'll have to follow at one point, I know that :) It's a lot of work though

I took a shot at the inline text editor, and wysihtml it is very interesting, not too painful integration in silex. You can play with bold, italic, underline, h1-h3 and lists here:
https://silex-test-tmp.herokuapp.com/

Let me know what you think?

**Comment by budislav** [comment]
>  Maybe in the menu bar on top of the stage? Don't you think it is better like it is now because it stays with the style editor? People will probably understand that it is linked together.

No because there are also settings for bold and italic already under the font style label and they are on the right place and there are same group of buttons already (p a b u i h1 h2 h3 ul ol) so it is confusing what to use.
I just mean when using bold, italic, insert link, wrap with span, and clear formating should be easily accessible just right under or above the word you select. Those settings are more often used. Like I said Webflow is the best example what we need but if positioning is a problem, we can have this like you made it now in style editor, it is better then before.

**Comment by lexoyo** [comment]
Good morning

I am working on the links today

Here are the [possible attributes I found here](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element)

The ones I think we should keep - but I'm not sure

    href — Address of the hyperlink
    target — Browsing context for hyperlink navigation
    download — Whether to download the resource instead of navigating to it, and its file name if so
    ping — URLs to ping
    rel — Relationship between the location in the document containing the hyperlink and the destination resource

The less useful once according to me, what do you think?

    hreflang — Language of the linked resource
    type — Hint for the type of the referenced resource
    referrerpolicy — Referrer policy for fetches initiated by the element

I would add `title` to le the user add a tooltip on the link

I wanted to see how the link editor looks in webflow but I could not create a link with their  interface :face_with_head_bandage:

**Comment by budislav** [comment]
I see ping — URLs to ping is not supported in edge and safari but I would not say I like those browsers, for me they are not existing :) https://www.w3schools.com/TAGs/att_a_ping.asp

It would be good if Silex can support all html  and css  tags no matter if they are existing in some browser or not, we can have text beside those option (not supported in "browser names", or just icons of five main browsers: chrome, firefox, safari, opera, edge). 
But I really think before everything we need css grid.

**Comment by lexoyo** [comment]
Thank you for your feedback @budislav 
I have several bugs but the link editor is in its first version, [you can try it here](https://silex-test-tmp.herokuapp.com/)
![screenshot from 2018-08-07 16-41-51](https://user-images.githubusercontent.com/715377/43782957-cf5eec78-9a60-11e8-9f8f-06a22859d5e9.png)

**Comment by budislav** [comment]
Very nice!
But we need to have this under the settings tab, that's why we have it :) Style tab is for css styles and settings tab is for html attributes settings.
So when user click on "a" button it should open settings tab with these settings.

**Comment by lexoyo** [comment]
> But we need to have this under the settings tab, that's why we have it :) Style tab is for css styles and settings tab is for html attributes settings.
> So when user click on "a" button it should open settings tab with these settings.
> So we can easily see and change those settings in any moment. Now you need to click again on a button which is already activated and that is not good.
> So this tab should be filled with this nice content :) So when you double click on hat linked text you made settings for that link will be shown there. That is how it should work for each html component.

That is interesting... Let's discuss that please

Untill now I see  the tab with the "A" as a tab for text styles, not all css styles. 
The problem I see in your solution is that params tab is dependent on the selection on stage, where the format section is dependent on the text selection in the text box. also the format section has the same tags which you can style in the style editor...

Also technically the 2 panels are very different: the format section is made by hand to integrate wysihtml editor, and the params tab is created with prodotype which generates this reactjs-based form based on a text file discribing the component. This makes it easy to create new components

Let me think about all this please. And if anyone has thoughts about how we should organize the panels, please share

**Comment by lexoyo** [comment]
I understand your point about webflow and I am currently watching their videos to get inspired, thank you
Please consider

* webflow probably has more than 50 developers and QA egineers full time on their editor
* we are creating our tool for ourselves, so Silex should be developed based on a "I develop what I need when I need it"
* the vision / direction we took since the beginning (2002) was the one which inspired wix: everything should be absolute because this is more intuitive in most cases - and it can be turned to positioned automatically in most cases

I just added images into text fields, but I am not sure that it is really useful as I did not add the options to have text around it... I will publish it and you will tell me? Also the UI with only letters seems not very intuitive to me (P, B, I...). Maybe an onboarding will be necessary (https://github.com/silexlabs/Silex/milestone/8)

**Comment by budislav** [comment]
I think there is no point going on without any right goal, direction. If that statement "I develop what I need when I need it" describing foundation of Silex than I can't tell I see a bright future of it.

We have Webflow for inspiration, but we can't use any model because Silex is not intended to be like that on the first place, so it can't adopt many essential things, because of Silex wrong foundation. Web technology is changing as design and coding principles almost every day, Silex need to follow everything.

Absolutely positioned pages are not good choice, that model is not good for modern websites, nobody is making website like that today and i don't believe if they ever in past, also not believe in future they will. So that's first thing we should think of, layout, structure, grid (css) box model, base...

In other words I think we really need new engine that could support all new essential things, that would require I can't imagine how much time but I think that is necessary for future of this project, for each next step, because just adding new features random in this kind of model is for me going back.

It would be just more and more harder and impossible to implement it on right way. There will just be so much hours invested into this direction so it would be impossible to think of making some radical changes, because that will involve erasing or changing lines and lines of code.

> I just added images into text fields, but I am not sure that it is really useful as I did not add the options to have text around it... I will publish it and you will tell me? 

Sure I will tell you, but I believe there is nice css thing called clip path https://bennettfeely.com/clippy/,
please watch this video https://www.youtube.com/watch?v=w8pksaGhjfA. She is a mozila developer, please look at others videos on that channel.

They are really educational and giving you a full picture of modern web designing, that is really necessary to understand, I am watching also this course https://www.udemy.com/advanced-css-and-sass/ and it really giving me totally new way of thinking about how website should be designed (coded and everything).. 

You see new technology is coming everyday, we need to catch it if we want this project be super awesome which I believe you want as me. To attract developers and designers, not just regular people. So when I export code from Silex it should be clean, simple html and css with all html5 code for google seo ready to go. So I can just convert it to scss easily without need to rebuild whole thing from scratch, than whole editor doesn't have a point. Also powerful editor so i can do there everything for front-end easily. Css is becoming more and more powerful everyday, we can build Silex even better than webflow but first it need to have many things at the same level.

**Comment by lexoyo** [comment]
I know, it's not perfect :-/ But it's there for a decade and the only free alternative to wix for DIY, so we have to continue ;)

Almost done with a 1st version of the text editor and styles
https://silex-test-tmp.herokuapp.com/

**Comment by lexoyo** [comment]
after some tests, here is what I think is missing, what do you think?

* [ ] float left/right for images in text boxes (where? how?)
* [ ] link editor should be also used outside the text, when attaching a link to an element (currently there is a dropdown list)

Also maybe make the UX better?

* [ ] tool tips or something to make it obvious that the styles button bar is for formatting selected text
* [ ] a marker to signify when a text box has focus and the text is being edited (or is it me?)

Nice to have

* [ ] a "colums" style in the style editor

**Comment by lexoyo** [comment]
float left/right for images is added

I pushed it on preprod, here are the code changes: https://github.com/silexlabs/Silex/pull/789

could someone test the new text editor and style manager please?
https://preprod.silex.me/

**Comment by clemos** [comment]
I had a quick look yesterday.

I find it weird that the style editor is not in sync with the text editor, ie when you format your text to H1, I think H1 should also be the selected style ?

Also, selected text is lost when you work on the style editor, which is very inconvenient.

The "Style name" part is quite confusing: 
* is the class applied to the whole text block ?
* what is the "phone" button supposed to do ?
* where are the styles stored ? where can I edit them ?

Something I don't understand either: when adding a new Text style (duplicate or "+"), the "style" part disappears ? Then you have to re-select a text box for the style editor to reappear.

**Comment by lexoyo** [comment]
Wow great comments @clemos thx
I'll answer each question but the general idea was

* Format block is in sync with the selection and used to change text box content's markup
* Style manager makes it possible to define and apply css styles to text boxes, with a context - mobile or desktop, and a state - normal, hover, other css pseudo classes

The idea of syncing the style editor and the selection is interesting! And this is easy to fix: "selected text is lost when you work on the style editor"

>     is the class applied to the whole text block ?

Yes and you'll find the style name in the text boxes CSS class property

>    what is the "phone" button supposed to do ?

It is on when editing the mobile version (mobile editor turned on). Then you are editing styles for the mobile site only

>    where are the styles stored ? where can I edit them ?

They are stored in as json in the website data. Also they are inserted as css styles in the website, and after publish they will be in a separate "css/styles.css" file

> Something I don't understand either: when adding a new Text style (duplicate or "+"), the "style" part disappears ? Then you have to re-select a text box for the style editor to reappear.

Oh that's a bug, thx
The rename seems to have this too
It should apply the style to the selected text box(es) and display the style right away

**Comment by lexoyo** [comment]
Here are ideas of what could be done to address these issues, let me know if you have other ideas @clemos and what you think about the list of ideas bellow @clemos @budislav @ceubri @BaguetteAgile @JbIPS 

1- sync the selection in the text box with the style manager, so the 2 button bars would be always showing the same thing and we should remove the 2nd one? 
  ![screenshot from 2018-08-25 17-54-35](https://user-images.githubusercontent.com/715377/44620177-196b0080-a890-11e8-83f1-f1ffd9bf4378.png)

2- move the format block (![screenshot from 2018-08-25 17-56-27](https://user-images.githubusercontent.com/715377/44620188-3b648300-a890-11e8-8131-cb1a8e02b7e2.png))
  2.1- to the context menu (![screenshot from 2018-08-25 17-56-54](https://user-images.githubusercontent.com/715377/44620192-461f1800-a890-11e8-816f-12087c89d47c.png))
  2.2- or on stage, on top of the text box (
![screenshot from 2018-08-25 17-58-59](https://user-images.githubusercontent.com/715377/44620211-9eeeb080-a890-11e8-9a9c-4673987bd4c5.png))
  2.3- or on stage, on top of the selection (
![screenshot from 2018-08-25 18-00-19](https://user-images.githubusercontent.com/715377/44620218-bfb70600-a890-11e8-91ab-77aded89fde4.png))

3- maybe an onboarding mechanism is needed to answer some of @clemos questions the first time a user edits a text box, like the tooltips suggested in #774 

Let's discuss all this quickly so that I can do it while I have time

**Comment by clemos** [comment]
I looked into it again:
Opening cleansquare template, double-clicking on a text box, the style of the text changes significantly, effectively breaking the template.

I think it's already quite difficult to apprehend because it mixes box-level settings with selected text formatting.
I think box level (including style editor ?) should be in the first tab (box tab?), and thus replace / enhance the current "styles" dialog.
In this context, (1) would make sense too.

Then you have only text formatting stuff left in the second tab, so you can indeed move it somewhere else.
Personnally, I prefer the 2.2 option.

3 is probably a good idea, but IMHO will never replace a clearer UI :D

**Comment by lexoyo** [comment]
Great @clemos thx

The template being broken is because the template was made with the old text editor and has non-standard markup (<font> tags). We will need to change all the templates before putting this on editor.silex.me 

To summarize what you advise

* [ ] The text style editor in a separate tab is a bad idea, let's have all the styles in 1 tab like in webflow - in the long run, I would like to make all the editors with prodotype so this makes even more sense. A question: what should I display when no text box is selected?
* [ ] keep the style editor in sync with the selection in the text box
* [ ] Make the format editor a floating bar

**Comment by clemos** [comment]
> The text style editor in a separate tab is a bad idea, let's have all the styles in 1 tab like in webflow - in the long run, I would like to make all the editors with prodotype so this makes even more sense. A question: what should I display when no text box is selected?

It's not necessarily a bad idea to have text formatting in a separate tab,
my point was rather that all things relative to the box should be in the same tab for consistency.
Text formatting in a separate tab makes sense, it's really the "Style name" dialog that feels weird.

The rest is correct.

**Comment by lexoyo** [comment]
Hello
I finished the "Make the format editor a floating bar" task
This was quite a lot of work but it looks good: https://preprod.silex.me/
What do you think @clemos @budislav @ceubri @BaguetteAgile @tariqbenezza ?
1- is the floating mode ok? you see bugs or unexpected things?
2- please test the text style editor and tell me how it works together?
3- what do you think about the idea of "keep the style editor in sync with the selection in the text box" ?
Thank you for your help!

**Comment by BaguetteAgile** [comment]
Hi, I just tested the text editor with the floating bar, great job,
 really good and make the text easier to edit.

I have not noticed any bug yet.

By cons, I have trouble understanding the operation of the link editor and advanced settings ...

**Comment by budislav** [comment]
Good job! style editor doesn't seems to work. Still think link settings and heading settings should be inside settings tab.

**Comment by lexoyo** [comment]
ok thank you for the feedback
i'll wait the one of @clemos too
here is mine after some experiments

1- I would like to add a style named "All style" which would be in all websites
  * display in style manager when the body is selected
  * in the website CSS, the selector should be `.silex-element-content > *` without a style name

2- the `P` selector in the style manager
  * should create a CSS style with the selector `.mys-tyle .silex-element-content > *` so that all the tags are styled by it, not only `P`
  * should be named `*` instead of `P`

What do you think about that?

**Comment by lexoyo** [comment]
> I have trouble understanding the operation of the link editor and advanced settings ...

Do you mean this?

![screenshot from 2018-09-06 11-07-44](https://user-images.githubusercontent.com/715377/45147392-1a236100-b1c5-11e8-910c-e59e165d0bc9.png)

**Comment by clemos** [comment]
> 1- is the floating mode ok? you see bugs or unexpected things?
It's nice, though not immediately noticeable, but I have no suggestion as to how to deal with that...

> 2- please test the text style editor and tell me how it works together?
(The second tab on the right ?) 
It works well, once you understand that it's a style editor and not a text editor :S 
I think it's a bit clearer now that in the previous version

> 3- what do you think about the idea of "keep the style editor in sync with the selection in the text box" ?
I think it would make sense.

I noticed a small bug: when you add a new text style (+), the tab becomes blank, like the style isn't initialized correctly.
Clicking on the refresh button makes it appear.

**Comment by BaguetteAgile** [comment]
yes that's it Alex,

in fact I do not understand all the possible options in the drop-down menu and in the advanced settings. 

But that may be due to my computer level? (or my english)

maybe insert a bubble info for each choice?
but it's not a priority at the moment.

Great job.

**Comment by lexoyo** [comment]
Great, thx a lot @budislav @clemos @BaguetteAgile 

You did not react to my proposal:

> 1- I would like to add a style named "All style" which would be in all websites
>
>   * display in style manager when the body is selected
>   * in the website CSS, the selector should be .silex-element-content > * without a style name
>
> 2- the P selector in the style manager
>
>   * should create a CSS style with the selector .mys-tyle .silex-element-content > * so that all the tags are styled by it, not only P
>   * should be named * instead of P

Concerning your feedback:

> @clemos 
> It's nice, though not immediately noticeable, but I have no suggestion as to how to deal with that...

You mean that you did not notice the floating bar immediately after double clicking the tex box?

> It works well, once you understand that it's a style editor and not a text editor :S

I can do this maybe

* [ ] add a link to the wiki in the style editor

> @BaguetteAgile 
> in fact I do not understand all the possible options in the drop-down menu and in the advanced settings.

* [ ] add a link to the wiki in the link editor

Do you think that a help link in the floating bar would be helpful ?

**Comment by lexoyo** [comment]
What I still want to change (thx @clemos) 
* [ ] B should be bold
* [ ] A blue and underlined or a link icon
* [ ] U underlined
* [ ] remove the "list-style-image" property

And one thing I have yet to choose: there is a problem if someone want to change the font familly for all the text in a text box, because all the styles (p, h1-h3, a ,ul...) have to be changed. So I can
* add a "default" font familly to the settings or somewhere
* add a "*" style which changes all the styles at once, or the "*" style can replace the "P" style?
* leave it like that

**Comment by lexoyo** [comment]
here is what I did today
* changed the design
* [added doc to the wiki](https://github.com/silexlabs/Silex/wiki/Editor-UI#6-text-fonts-and-styles-1)
* links in the text editor and link editor to the wiki
* the "P" style changes also the h1-h3 styles as if they were inside a p tag

Some documentation is still missing, I have written "help wanted" in the wiki where it is the case

I think it is ready to ship like this, could you test on a real life case @ceubri @BaguetteAgile @fernandammoutinhobarros ?

**Comment by BaguetteAgile** [comment]
Hi @lexoyo , 

I just tested (on my site)  the new text editor,
 frankly it's really great and editing is simple. 
the link to wiki is cool as well as the explanations for the links editor! 

I did not notice any bug

the wiki will be completed of course.

**For me the text editor is ready to go online.**

Very good work.

PS: where are we with text fonts?

**Comment by lexoyo** [comment]
Great thank you for the test Baguette
The fonts are nowhere for now :-/
I have not even found a website with open source fonts :-/

Le 11 sept. 2018 à 22:44, à 22:44, BaguetteAgile <notifications@github.com> a écrit:

**Comment by lexoyo** [comment]
> I noticed a small bug: when you add a new text style (+), the tab becomes blank, like the style isn't initialized correctly.
> Clicking on the refresh button makes it appear.

Fixed, thx @clemos

Le 6 sept. 2018 à 12:03, à 12:03, "Clément Charmet" <notifications@github.com> a écrit:

**Comment by clemos** [comment]
> I have not even found a website with open source fonts :-/

https://github.com/phax/ph-fonts for example
also, most fonts on fonts.google.com are either under Apache or Open Font licences

**Comment by lexoyo** [comment]
Thx @clemos !
The ph-fonts seems to be a Java project and fonts for PDF? I'm not sure how I can use it with Silex? You think I should host an instance of it somewhere and use the API?
For Google fonts, I'm worried about user privacy, what do you think?

Le 12 sept. 2018 à 12:59, à 12:59, "Clément Charmet" <notifications@github.com> a écrit:

**Comment by clemos** [comment]
I think you should just download fonts from google or ph-fonts, then host them somewhere on silex.me ?

**Comment by BaguetteAgile** [comment]
Hello , look at this link . 
I don't know,  if it's ok for  Silex. 

http://typotheque.interstices.io

**Comment by lexoyo** [comment]
> I think you should just download fonts from google or ph-fonts, then host them somewhere on silex.me ?

Oh ok I'll do that for now
And probably offer a way to add any font

> Hello , look at this link .
> I don't know, if it's ok for Silex.
> http://typotheque.interstices.io

Yes this is good!!

Now we need to select a few fonts

**Comment by BaguetteAgile** [comment]
> Now we need to select a few fonts

Hello everyone, here is my list of favorite fonts chosen on the site http://typotheque.interstices.io


> Baskervald
Averia
Inknut Antiqua
Playfair Display
Autopia
Open Sans

I am waiting for your comments.

**Comment by lexoyo** [comment]
What I'm doing before releasing this live

* [ ] default links style is bad (at least leave the underline)
* [ ] impossible to style active links
* [ ] it still needs good fonts
* [x] link editor looks strange
* [ ] all templates need to be adapted to use the new style editor

**Comment by jotakar** [comment]
I would like an easier installing process. So, we could have the option to download the full code in a zip file and then upload to server (external or  local server), config it and run. I man some way to install by hand.

**Comment by lexoyo** [comment]
Hey all

I have added a column style for texts, it is quite powerful and took me only an hour to add

![screenshot from 2018-09-19 18-04-13](https://user-images.githubusercontent.com/715377/45765894-82972700-bc36-11e8-89cd-8ab2106b54a3.png)

And also a new "tag" to style the links which lead to the current page, which is very useful to tell visitors which page they are in... In the nav bar for example

![screenshot from 2018-09-19 18-26-46](https://user-images.githubusercontent.com/715377/45767172-c3dd0600-bc39-11e8-8022-bb55a39dd916.png)

Would someone test these 2 new features?
https://preprod.silex.me/

**Comment by lexoyo** [comment]
Hello
I have created a "All" tab to style all texts at once.
Also I reorganized and put a help link
What do you think?
![screenshot from 2018-09-20 12-01-30](https://user-images.githubusercontent.com/715377/45811261-eec46a00-bccc-11e8-9519-3cc47eb71bdf.png)

**Comment by lexoyo** [comment]
(it's live on https://preprod.silex.me/ )

**Comment by fernandammoutinhobarros** [comment]
This is very good!

**Comment by budislav** [comment]
On Firefox 62.0 (64bit), win10
![bug](https://user-images.githubusercontent.com/3619927/45812122-2d5b2400-bccf-11e8-98f4-ec160ddd11e1.png)

**Comment by lexoyo** [comment]
@budislav you need to empty your cache

**Comment by lexoyo** [comment]
Haha thx @fernandammoutinhobarros

Working on embedded fonts now

**Comment by lexoyo** [comment]
I did one last thing: a new font manager
![screenshot from 2018-09-21 13-45-41](https://user-images.githubusercontent.com/715377/45879397-a6787b00-bda4-11e8-9c9b-936d337fff24.png)

I need testers! And I need to know if you can understand how it works easily?

**Comment by Tomygg** [comment]
I can't connect my website with https://preprod.silex.me. When I click on "Import",  it's just blanc, nothing happens. One more thing - current text editor is very bad. I had one issue, where the text copied from word to text editor had bunch of unnecessary code left in published index file, which filled up my quota. I had to redo all my pages with text simply copying text from word to Notepad and then to text editor. And this way I saved HALF!!! of the index file size. Yes, you heard it right. 400 Kb. of index file size was taken up by this bug.

**Comment by Tomygg** [comment]
Big thanks to lexoyo who spotted the bug and helped me fix the problem. I don't know how I would have gone around this without him.

**Comment by lexoyo** [comment]
> I can't connect my website with https://preprod.silex.me. When I click on "Import", it's just blanc, nothing happens.

thx @Tomygg for the bug report
the issue was in cloud explorer and it is now fixed, you can use preprod.silex.me

> One more thing - current text editor is very bad. I had one issue, where the text copied from word to text editor had bunch of unnecessary code left in published index file, which filled up my quota. I had to redo all my pages with text simply copying text from word to Notepad and then to text editor. And this way I saved HALF!!! of the index file size. Yes, you heard it right. 400 Kb. of index file size was taken up by this bug.

In fact it is not really a bug, but a feature which has the new text editor: it detects paste actions and filters the input. So you do not need notepad anymore :v: 

FYI I'm still trying to release the new text editor version. Right now I have to go through all the templates and remove the CSS and re-do it with the style editor. It is much better but takes a long time...

I'm still wondering if the style editor will be understood by the average Silex user... Maybe it doesn't matter.. Anyway it is probably better than before

Any more tests are welcome!

**Comment by fernandammoutinhobarros** [comment]
Dear @lexoyo ,
Wen I open my editable file, I can't see my website pages.
I there a problem with silex?

![image](https://user-images.githubusercontent.com/25388113/47507993-2a71c700-d86b-11e8-89bd-3b184a42233d.png)

**Comment by lexoyo** [comment]
Hi @fernandammoutinhobarros 
Can you try again?
Because as I said to @rijschoolthomas [here](https://github.com/silexlabs/Silex/issues/814#issuecomment-433404039)
> I switched Silex Labs server to heroku and it stops working from time to time until I reboot the server... I've setup alerts in order to find out what is happening. I'll let you know how goes, please let me know if something changes
Thank you!

**Comment by fernandammoutinhobarros** [comment]
Hi @lexoyo 

Still the same, and I have tried to use older file, and they are all the same.

**Comment by lexoyo** [comment]
is it in your dropbox? which files?

**Comment by fernandammoutinhobarros** [comment]
I've placed a copy a them on the folder editable

**Comment by lexoyo** [comment]
@fernandammoutinhobarros I'll need more details, I tried them all and it works for me

![screenshot from 2018-10-28 16-08-30](https://user-images.githubusercontent.com/715377/47617826-ce59ad80-dacb-11e8-91d8-b63347fb898d.png)

can you tell me which browser or files or any more details? maybe open the javascript console of your browser and make a screenshot?

**Comment by rijschoolthomas** [comment]
Hi Alex, i think you may have sent this to the wrong person. I'm Michael
from @rijschoolthomas

Op zo 28 okt. 2018 16:09 schreef Alex Hoyau <notifications@github.com>:

**Comment by fernandammoutinhobarros** [comment]
Ok, didn't think it could be the browser.
On Chrome it's not showing the pages.
On Mozzilla it's ok!

![image](https://user-images.githubusercontent.com/25388113/47647724-c05d6880-db6f-11e8-801a-c94f0649ec45.png)

**Comment by fernandammoutinhobarros** [comment]
Image of the javascript console, with the editable open on silex editor


![image](https://user-images.githubusercontent.com/25388113/47648112-efc0a500-db70-11e8-9ec9-1f189699dfeb.png)

**Comment by lexoyo** [comment]
oh ok, i'll try with chrome then

**Comment by lexoyo** [comment]
@fernandammoutinhobarros I still can not reproduce the bug... Even on chrome
Which file is it exactly?

**Comment by fernandammoutinhobarros** [comment]
I restarted chrome, updated, but the problem still exists.

On the editable folder, all the files give the same problem.

Tested on Opera and the same happens.

In Mozzilla is working fine.


Opera Browser
![image](https://user-images.githubusercontent.com/25388113/47654822-9150f200-db83-11e8-8a19-f959ea003ae2.png)

**Comment by lexoyo** [comment]
@fernandammoutinhobarros I still need to sort that out, thank you very very much for testing on preprod.silex.me

@all there is a new version to test with firefox only
It has the new templates and the style editor should work on all of them now (cc @jotakar you can test now :))

Please test as this is a major new release coming soon :1st_place_medal: 
https://preprod.silex.me/

![screenshot from 2018-11-07 18-33-24](https://user-images.githubusercontent.com/715377/48149132-a92f2100-e2bb-11e8-8e1f-4bfcd550cffe.png)

**Comment by fernandammoutinhobarros** [comment]
Ok.
Thank you for your hard work!

**Comment by lexoyo** [comment]
Ok, I will release the new version very soon
Last chance to test on preprod.silex.me ;)

**Comment by jotakar** [comment]
Mmmm... it looks cool, thanks you are a hard worker ;)

**Comment by jotakar** [comment]
As a contribution: I've found the same problem in th install process as in previous versions: node-sass and access error (write permissions). (Linux, node 8.12, npm 6.41)
If ti's a general problem, and not just a problem for my system, I would modify documentation about install process in a linux server:
Prerequisites:
Node
Npm
Python
Java
gcc (c++) compiler

Install as a **non root user** with write/read access to silex files and folders. 
Before installing silex i's needed to **install node-sass** (npm install node-sass)
That is my experience with this last (and very good) version
I see text editor is now working fine. Good!!!.

Thanks again for your work.

**Comment by lexoyo** [comment]
thx a lot @jokatar for the bug report and cheering me up :)

I have added these warnings to [the documentation here](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#local-installation-on-linux-or-macos-or-cloud9) ([diff](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex/_compare/5f53576a556856645ee465234e370f5e628851ad))

And I have also deployed the new version: it is live on https://editor.silex.me and the code is on the master branch

**Comment by lexoyo** [comment]
This is live on https://editor.silex.me
Please test on your websites and open new issues when you find bugs
Also [have a look at the docs here](https://github.com/silexlabs/Silex/wiki/editor-ui#text-editor) and add it if something is missing

Thx team! It is a 4 month-big development!!!
:fireworks:

**Comment by fernandammoutinhobarros** [comment]
Hi @lexoyo ,
 I'm testing... starting to understand :+1:
