### ISSUE TITLE
Cancel button on file explorer does not work - causes you to lose your work

### ISSUE THREAD

**Issue by lindstromscott** [silexlabs/Silex#796]
If you are editing a website and accidentally click on "file explorer," you lose all of your work, because the file explorer menu comes up and cannot be dismissed with the "cancel" button. The cancel button has no effect, and you cannot get out of the file explorer menu without reloading the page. As a result, you cannot save your work and lose all work.

**Comment by lexoyo** [comment]
Hi @lindstromscott 
Thank you for taking the time to report the bug
I have fixed this bug a week ago, what version of Silex are you using? Are you on editor.silex.me ?

**Comment by lindstromscott** [comment]
Yes; the editor I am using is editor.silex.me. Has this been deprecated?

**Comment by lexoyo** [comment]
> Has this been deprecated?

No it's still the correct address
But the bug is fixed there... Can you try to emty your browser's cache, reload Silex and check if it is fixed please?
What is your browser?

**Comment by lindstromscott** [comment]
Browser is chrome. Just cleared the cache; it's still broken.

**Comment by lexoyo** [comment]
oh ok i can reproduce it
if you press "ESC" on your keyboard it closes cloud explorer but if you click cancel it "freezes"
thank you for the report !

**Comment by lindstromscott** [comment]
No problem. Also, if you press "ESC" after first clicking "cancel," it
stays stuck. You must press "ESC" without clicking "cancel" in order to get
out successfully.

**Comment by lexoyo** [comment]
Ok, it looks like the fix has been removed from master somehow... It is still on develop though
Could you please confirm that you don't have the bug there?
https://preprod.silex.me/

**Comment by lindstromscott** [comment]
On prepod, I don't have the bug.

**Comment by lexoyo** [comment]
Ok good then
This should be fixed on editor.silex.me too now
