### ISSUE TITLE
Mobile usability

### ISSUE THREAD

**Issue by rijschoolthomas** [silexlabs/Silex#843]
Hi guys and of course Dolls,

Google is badgering me about Mobile usability. 

Google has told me that:
1 - my Viewport is not set to the "device-width"
2 - the content is wider than the screen

Can anybody see what seems to be the problem and tell me how to fix it please? I need for google to index my site without penalizing me because it finds something wrong. I'm dependent on customers finding my driving school site.

Thanks,
Michael

**Comment by lexoyo** [comment]
Hi
I checked and 
1- there is a viewport tag like this: `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2.2">` do you think it is wrong?
2- on mobile the content is not wider than the screen
How did google warn you? by email?

**Comment by rijschoolthomas** [comment]
Hi Alex,
In answer to your 2de question; Google warned me via my Google Search
Console.

The warning message was ( and this is a translation from the Dutch
language):
--------------Message------------------------
New (Mobile) mobile usability issues detected for site
https://rijschoolthomas.com/28 November 2018
To: Owner of https://rijschoolthomas.com/,

Search Console has determined that your site is affected by 2 new Mobile
usability-related problems. This can have negative consequences for Mobile
usability in Google search results. Check and correct these problems.

Top 2 new problems that have been found, ranked by number of pages:

1 -  Content wider than screen

2 - Viewport is not set to "device-width"

-------------------------End of message----------------------------------

In answer to your first question if the meta you found is wrong:
As you know I'm not an expert but i found the following when going to
google solutions for my meta and page problems:

Set the viewport
Pages that have been optimized for different devices must have a
meta-viewport element in the head of the document. A meta tag for viewport
gives the browser instructions on how to manage the size and scalability of
the page.

TL, DR
Use meta tags for the viewport to determine the width and scaling of the
browser service.
Include width = device-width to adjust the width of the screen in
device-independent pixels.
Include initial-scale = 1 to obtain a 1: 1 ratio between CSS pixels and
device-independent pixels.
Make sure your page is accessible by not turning off scaling for users.
In an attempt to deliver the best experience, mobile browsers display the
page with the width of a desktop screen (typically about 980 pixels, but
this varies per device) and then try to better display the content by
increasing the font size and content to adjust the screen. Users see that
the font sizes are inconsistent and need to double-tap or pinch to zoom so
they can see the content and respond to it.

<meta name="viewport" content="width=device-width, initial-scale=1.0">

By using the meta-value for viewport width = device-width, the page is
instructed to match the width of the screen to device-independent pixels.
This allows the page to dynamically adjust the content so that it fits into
different screen sizes, both on a small mobile phone and on a large desktop
screen.

*Alex this is wat seems to happen to the silex mobile (at least it does on
my site)*--->When switching to landscape mode, some browsers retain the
width of the page and zoom in on the content instead of dynamically
adjusting it to fill the screen. The initial-scale = 1 attribute instructs
browsers to set a 1: 1 ratio between CSS pixels and device-independent
pixels, regardless of the device orientation. The page can then make
optimum use of the full horizontal width.

Alex, this is the link tot the hole "Basic principles for responsive web
design" (of course it is in Dutch):
https://developers.google.com/web/fundamentals/design-and-ux/responsive/

I hope it helps you...


Cheers,

Michael




Met vriendelijke groet,

*Michael Thomas*


Op vr 30 nov. 2018 om 15:53 schreef Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
hi @rijschoolthomas 
I can reproduce that on 1 of my website (not all just 1)
I'm on it

**Comment by lexoyo** [comment]
i tried hard today to understand what googlebot mobile does...

I could fix the "Viewport is not set to "device-width"" by replacing silex's viewport tag with `<meta name=viewport content="width=device-width, initial-scale=1">`

But I still have strange results when I test the site on which I can reproduce your bug with google tool:
https://search.google.com/test/mobile-friendly?url=http%3A%2F%2Flexoyo.me%2Flanding-page%2F

It is as if googlebot mobile ignores media queries... I have to stop for now, let me know if someone has an idea

**Comment by lexoyo** [comment]
@rijschoolthomas could you open your website in editor.silex.me again and publish it live?
i tried to fix the 2 most anoying issues (content wider than screen and viewport)

**Comment by rijschoolthomas** [comment]
HELP!!!, my pictures are now not loading into the website.
I saved and then published but no pictures anymore.

rijschoolthomas <https://github.com/rijschoolthomas>/website
<https://github.com/rijschoolthomas/website>
https://rijschoolthomas.com/

Met vriendelijke groet,

*Michael Thomas*


Op zo 16 dec. 2018 om 20:46 schreef Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
oh something went wrong
silex is looking for the images in /test2/master/assets/Dakbord-achter.jpg
did you move the website from a folder to another?
i will look into it now

**Comment by lexoyo** [comment]
Ok good :)
If you used editor.silex.me to publish the issues should be resolved (did you refresh your browser window to update silex?

Le 17 déc. 2018 à 06:29, à 06:29, Michael Thomas <notifications@github.com> a écrit:

**Comment by rijschoolthomas** [comment]
Update browser window? Don't think so.

Op ma 17 dec. 2018 06:33 schreef Alex Hoyau <notifications@github.com:

**Comment by lexoyo** [comment]
You should at least refresh the page to have the latest changes

Le 17 déc. 2018 à 07:43, à 07:43, Michael Thomas <notifications@github.com> a écrit:

**Comment by rijschoolthomas** [comment]
Thanks Alex,
It's working. Rijschoolthomas.com . I can now zoom in and out on my mobile.
And google has stopt complaining about those 2 issues.

I still can't find the slider element that is causing those arrows and also
there's now a large white space at the underside on the mobile that i can't
seem to get rid of.




Op ma 17 dec. 2018 12:10 schreef Alex Hoyau <notifications@github.com:

**Comment by lexoyo** [comment]
> It's working. Rijschoolthomas.com . I can now zoom in and out on my mobile. And google has stopt complaining about those 2 issues. 

yeah :D

> I still can't find the slider element that is causing those arrows 

in mobile editor, you don't see it?

> and also there's now a large white space at the underside on the mobile that i can't seem to get rid of.

yes I know, it is a side effect of my bug fix :-/
I'll try to figure something out

I'll close this issue, feel free to open new ones for other problems you may have

**Comment by rijschoolthomas** [comment]
in mobile editor, you don't see it?

No i can't find it. I've gone through the site page by page.

Op di 18 dec. 2018 16:35 schreef Alex Hoyau <notifications@github.com:
