### ISSUE TITLE
Local Install failed with cloud-explorer - Windows

### ISSUE THREAD

**Issue by ruchiordex** [silexlabs/Silex#931]
Hi
I am facing error for cloud-explorer while installation in local.
 
Here i have used following:
Windows version-8.1
Node version-8.10.0
Npm version-5.6.0
Reference link which i have used for installation: https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex

![image](https://user-images.githubusercontent.com/25473949/57215925-035f3380-700c-11e9-81d7-119eaa41febf.png)

**Comment by lexoyo** [comment]
so you did `npm install -g silex-website-builder` ?

**Comment by lexoyo** [comment]
ok i think i found a bug in the npm package
now it should work like this:
```
$ npm install -g silex-website-builder
$ silex

```

**Comment by sidjai09** [comment]
Hi @lexoyo First of all thank you for your help!

As you said I had done the same steps but still facing the same error.
Is there any other way?

![image](https://user-images.githubusercontent.com/46618565/57272837-eb8eba80-70b2-11e9-903a-0a5a84955616.png)

**Comment by ruchiordex** [comment]
Hi @lexoyo, first of all, thank you for your help!

As you said I have followed the same steps but still facing the same error.
Is there any other way?

![image](https://user-images.githubusercontent.com/25473949/57272942-7bccff80-70b3-11e9-975c-d99492c444ca.png)

**Comment by ruchiordex** [comment]
Hi

Also, I am trying to integrate silex with angular web app. Can you pls guide me on same? If possible with the link that helps me with proper steps.

**Comment by lexoyo** [comment]
> As you said I have followed the same steps but still facing the same error.

So you did it again and it gave this error? Are you sure? Maybe it is windows 8... @jbIPS would you have time for a very little test on Windows? (npm install -g silex-website-builder && silex)

> Is there any other way?

You can try the other methods of
https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex

Including electron app and Docker

Or you can use https://editor.silex.me

> Also, I am trying to integrate silex with angular web app. Can you pls guide me on same? If possible with the link that helps me with proper steps.

Let's talk about that in another issue please, as soon as you have Silex working

**Comment by Certroyer** [comment]
The problem may lie in the node-sass command. It seems windows can't handle those backticks.
The following kinda works, but I'm not sure if this is the correct way.
`node-sass --include-path ../font-awesome --include-path ../npm-font-open-sans ./src/sass/style.scss ./dist/style.css`

Prodotype has a similiar syntax in its package. You will face another problem if you get around the sass error:
```
> browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && cat `node_modules ejs`/ejs/ejs.min.js >> pub/prodotype.js

cat: `node_modules: No such file or directory
cat: ejs`/ejs/ejs.min.js: No such file or directory
```

I installed the silex-website-builder sucessfully on a debian machine, copied the files to a windows machine and rebuild node-expat and iconv.
Finally I was able to start the server and see the website... without any templates:

```
> FTP service disabled, env vars ENABLE_FTP not set
> SFTP service enabled
> Webdav service disabled, env vars ENABLE_WEBDAV not set
> Github service disabled, env vars GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET not set
> Dropbox service disabled, env vars DROPBOX_CLIENT_ID and DROPBOX_CLIENT_SECRET not set
> Local file system service disabled, env vars SILEX_ELECTRON or SILEX_DEBUG or ENABLE_FS not set
> Adding hosting provider Choose a folder
> Force SSL option is disabled, env var SILEX_FORCE_HTTPS not set
> SSL certificate disabled, env vars SILEX_SSL_CERTIFICATE and SILEX_SSL_PRIVATE_KEY not set

I'm ready, listening to port 6805

Silex server started
Error while trying to get the json representation of the folder  S:\silex\node_modules\silex-blank-templates
Error while trying to get the json representation of the folder  S:\silex\node_modules\silex-templates
````

**Comment by lexoyo** [comment]
oh wow :-/
I'll try to publish compiled projects on npm now (prodotype and cloud explorer and unifile are maintained by silex team too)

> Error while trying to get the json representation of the folder  S:\silex\node_modules\silex-blank-templates
> Error while trying to get the json representation of the folder  S:\silex\node_modules\silex-templates

Does the folders exist? (silex\node_modules\silex-blank-templates)

**Comment by Certroyer** [comment]
> Does the folders exist? (silex\node_modules\silex-blank-templates)

Yes it does. The same goes for *silex\node_modules\silex-templates*. Both contain the same content as the one on the debian  system. I installed both template modules on the windows system again. Still no luck.

**Comment by lexoyo** [comment]
What I just did:

* changed cloud explorer to include compiled files
* publish cloud-explorer version 2.0.2 on npm
* published silex-website-builder 2.5.12 on npm with the latest cloud-explorer version

So now you should not need node-gyp which was required by node-sass which is not used when `npm install` anymore

**Comment by Certroyer** [comment]
Thanks for the update. A clean install of silex-website-builder does not throw any more errors related to cloud-explorer. Some problems still remain:

```
> prodotype@1.0.2 build:editor S:\silex\node_modules\prodotype
> browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && cat `node_modules ejs`/ejs/ejs.min.js >> pub/prodotype.js

cat: `node_modules: No such file or directory
```

- removing the backticks fixed that.

```
> drag-drop-stage-component@1.0.2 install:redux S:\silex\node_modules\silex-website-builder\node_modules\drag-drop-stage-component
> cp `node_modules`/redux/dist/redux.min.js pub/redux.js ; echo 'Last command can fail if stage is a depenency'

cp: target „Last command can fail if stage is a depenency“ is not a directory
```

- removing **;** and the echo command fixed that

```
> drag-drop-stage-component@1.0.2 prebuild S:\silex\node_modules\silex-website-builder\node_modules\drag-drop-stage-component
> mkdir -p pub/js && npm run install:requirejs

syntaxerror
```

Windows has problems with mkdir, probably because of its inbuild command. Installing the package [mkdirp](https://www.npmjs.com/package/mkdirp) and replacing all occurrences of *mkdir* and *mkdir -p* with *mkdirp* fixed that. (package.json of drag-drop-stage-component and silex-website-builder).

Finally you can start the server. The template error still exists though.

**Comment by ruchiordex** [comment]
> Are you sure that `npm install -g silex-website-builder && silex` command does not work on Linux?



> With a node version which is supported

Yes, here I have used the same version which is supported still getting the error.

**Comment by ruchiordex** [comment]
Hi @Certroyer 

For Windows

I have pulled the latest code from "develop" branch.

And facing the same issue as you mentioned 
> prodotype@1.0.2 build:editor S:\silex\node_modules\prodotype
> browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && cat `node_modules ejs`/ejs/ejs.min.js >> pub/prodotype.js

and also tried to solve that as you did but after removing the backticks nothing happened it shows the same error.

**Here is my path for removing backticks "E:\Silex\node_modules\prodotype\package.json"**

**and also not found "silex-website-builder" folder in node-module. So not able to do anything here**

> drag-drop-stage-component@1.0.2 prebuild S:\silex\node_modules\silex-website-builder\node_modules\drag-drop-stage-component
> mkdir -p pub/js && npm run install:requirejs

So please let me know if I am doing something wrong here.

![image](https://user-images.githubusercontent.com/25473949/57447704-4a039680-7275-11e9-92ff-63d2bc81c8a3.png)

**Comment by Certroyer** [comment]
Hi @ruchiordex,
as lexoyo mentioned the backticks version is short for _.bin_ path, meaning you should replace
```
cat `node_modules ejs`/ejs/ejs.min.js >> pub/prodotype.js
```
with 
```
cat ./node_modules/.bin/node_modules/ejs/ejs.min.js >> pub/prodotype.js
```

I do not install silex-website-builder with the global argument, but with the -S mentioned [here](https://github.com/silexlabs/Silex/wiki/How-To-Add-Silex-To-Your-Node.js-Project). Therefore the paths may differ. However, if a module is missing you can install everything again with 
```
npm install -g silex-website-builder --ignore-scripts
```
edit the package.json files and try to install it again (without --ignore-scripts)

**Comment by ruchiordex** [comment]
Yes solved that prodotype error!
Thanks for that

And also tried to install everything again but still facing issue on "drag-drop-stage component" as that silex-website-builder not found

![image](https://user-images.githubusercontent.com/25473949/57455088-fea6b380-7287-11e9-93ae-4f2a2a9256c8.png)

**Comment by Certroyer** [comment]
Does that mean that you are missing the _drag-drop-stage-component_ module?
Go into the directory where the silex-website-builder package.json lies and enter:
```
npm install --ignore-scripts
```
That should add it. Open the package.json lying in node_modules/drag-drop-stage-comonent and edit the lines with the backticks. Going back to the root path and hitting **npm install** again should work now.

Hopefully you won't face the same problem with mkdir as I did.

**Comment by lexoyo** [comment]
Hi guys
I really would like that to work for everybody

What I did:
* cleaned up some things in drag-drop-stage-component (including a big dirty workaround for a bug which has been fixed in jest) and made sure that now every built file is committed in npm, so no more build
* same for Prodotype, no more compilation needed on npm i
* I made sure that when you install silex as a dependency or globaly, nothing more than what is really needed is run and no more ``` ` ``` should bother you

Could you please retry without workarounds?

**Comment by Certroyer** [comment]
Hi @lexoyo,
almost there. I can confirm that the installation works perfectly fine on Windows Server 2016 and Windows 7 Professional. No problems starting the server either. However, both do not show any templates:

```
I'm ready, listening to port 6805

server started
Error while trying to get the json representation of the folder  S:\silex\node_modules\silex-blank-templates
Error while trying to get the json representation of the folder  S:\silex\node_modules\silex-templates
```

If you try to click on something like the import button, the following happens:

```
TypeError: Cannot read property 'handleError' of undefined
    at readTemplate (S:\silex\node_modules\silex-website-builder\dist\server\server\router\WebsiteRouter.js:70:38)
```

**Comment by ruchiordex** [comment]
Hi @lexoyo 

Working on Window 7 with fresh code.
 
![image](https://user-images.githubusercontent.com/25473949/57508693-d5396680-731f-11e9-80d1-4cd511451799.png)

Just hitting npm install and here is the error which I am facing.

![image](https://user-images.githubusercontent.com/25473949/57508987-ad96ce00-7320-11e9-83e9-5bd9e18446d8.png)

@Certroyer 
As you said
> Does that mean that you are missing the _drag-drop-stage-component_ module?
> Go into the directory where the silex-website-builder package.json lies and enter:
> 
> ```
> npm install --ignore-scripts
> ```
> 
> That should add it. Open the package.json lying in node_modules/drag-drop-stage-comonent and edit the lines with the backticks. Going back to the root path and hitting **npm install** again should work now.
> 
> Hopefully you won't face the same problem with mkdir as I did.

so now it shows that "silex-website-builder" and "drag-drop-stage-comonet".

**Comment by ruchiordex** [comment]
Hi @lexoyo 

Thanks!!!
Yes, now silex works on my local machine. Actually, there is an issue with node form my side. but now it's resolve and silex server start but facing the same error as @Certroyer said.

**Comment by lexoyo** [comment]
Ok I'll check this Monday
I'll have to install a windows VM, it's been a long time I didn't play with windows
I should have done this before publishing on npm

**Comment by lexoyo** [comment]
Hi
I took a shot, installed a windows VM (win 10)
It looks like npm needs git installed to get the templates, and this is probably because the templates are not real npm dependencies but git repos. So I published the templates to npm and included them in silex as normal dependencies. It should work now

**Comment by ruchiordex** [comment]
Hi @lexoyo 
Thanks for the update!

But I am facing the same error as above.

Here are the steps which I do.
1. Clone latest code from develop branch
2. Hit "npm install" command on the path where silex folder cloned
3. Here I am facing error which is

![image](https://user-images.githubusercontent.com/25473949/57597646-dfe93b00-756d-11e9-8dda-97762742de88.png)

4. After that, I was hit "npm install -g silex-website-builder && silex" command and silex server started but still face the same error for templates and import button as shown in the previous comment.

![image](https://user-images.githubusercontent.com/25473949/57597578-8aad2980-756d-11e9-8800-9c16be45803d.png)

Am I doing wrong anything here? Please let me know.

**Comment by lexoyo** [comment]
Oh ok I understand
The 2 methods are independent: either you do `npm install -g silex-website-builder && silex` or you clone the repo, not both
Can you try this please, from an empty folder (at least not from Silex git repo)
```sh
$ npm uninstall -g silex-website-builder
$ npm install -g silex-website-builder
$ silex
```
Also use nodejs 10 or close to 10

**Comment by ruchiordex** [comment]
Yes doing the same as you said
1. Create a new empty folder.
2. Hit below command on the same empty folder.
> $ npm uninstall -g silex-website-builder
> $ npm install -g silex-website-builder
> $ silex

 but still facing the same error (default template and import button not working).

Used node version: 10.15.3

**Comment by lexoyo** [comment]
I have even harder times than you do installing silex on windows 10 with a virtual machine

I'll ask you more tests but in the mean time some questions

1- What happens when you do `npm install -g silex-templates` and `npm install -g silex-blank-templates` ?
2- What happens when you do `npm install -g cloud-explorer` ?
3- What shell are you using? PowerShell?
4- Did you try to run your shell as admin?

**Comment by lexoyo** [comment]
Ok I think I nailed it... I managed to install a windows virtual machine and Silex with it

On the Windows side, I had to do [this which I added to the docs](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex/_compare/47a7a9342073532b8fe1325f7c0f188f11667efe...6d6858e75a6e969ce7233390882a5edff5295b1e
).

On my side, I found some "/" left here and there which do not work on windows of course, here are the changes I made:
* https://github.com/lexoyo/node_modules-path/commit/a7bce2f4476621db310657c9fbc7d2f25ad9b2eb
* https://github.com/silexlabs/Silex/commit/d153c40184a00bbdd595e85fcc44938cd7920c8e#diff-1ed37d65d5ee8d9c0ea1dcd9d7fb7b2eL28

You can do this and it should work
```sh
$ npm uninstall -g silex-website-builder
$ npm install -g silex-website-builder
$ silex
```

PS: interesting article about writing [cross platform nodejs](https://shapeshed.com/writing-cross-platform-node/)

**Comment by ruchiordex** [comment]
As you said I followed the same steps as below
 
> 1- What happens when you do `npm install -g silex-templates` and `npm install -g silex-blank-templates` ?
generated separate folders for silex-template and silex-blank-templates

> 2- What happens when you do `npm install -g cloud-explorer` ?
-generated cloude-explorer separate folder

> 3- What shell are you using? PowerShell?
    normal cmd

> 4- Did you try to run your shell as admin?
   no

1. As I have not used PowerShell so used that in administrator mode.
2. I have already installed MS build tools so nothing doing on that.
3. then run below commands respectively

	>npm uninstall -g silex-website-builder
	>npm install -g silex-website-builder
	>silex

4. It seems like not found the required folder for templates

![image](https://user-images.githubusercontent.com/25473949/57775728-525b4600-773b-11e9-879e-6a3162afff87.png)

Also, I have tried another method which is clone the repo
1. clone fresh code with "develop" branch
2. run npm install

here I am getting the same error as mention above below is the snapshot for same
 
> ![image](https://user-images.githubusercontent.com/25473949/57597646-dfe93b00-756d-11e9-8dda-97762742de88.png)

**Comment by lexoyo** [comment]
Oooo
Are you sure that you have the latest Silex and templates?
Maybe you can delete the folder node_modules and start fresh?

**Comment by lexoyo** [comment]
OMG, I had to install a win7 machine
Not sure why it worked on win 10 as [there was something wrong](https://github.com/silexlabs/Silex/commit/80eacca3ca3714ccc23e91b79fe02af4db35c2ac)
So now it should work ! Please try this again from PowerShell
```sh
npm uninstall -g silex-website-builder
npm install -g silex-website-builder
silex
```

**Comment by ruchiordex** [comment]
Yes, it's working!

Thank You So much for your help and support.

**Comment by Certroyer** [comment]
Thanks a lot! Can confirm it's working on Windows 7 and Windows Server 2016. I think the issue can be closed now.

BTW: Managed to host an instance with IIS as proxy. I would like to add it to the wiki.

**Comment by lexoyo** [comment]
Great, I'll finally close this :1st_place_medal: 

> BTW: Managed to host an instance with IIS as proxy. I would like to add it to the wiki.

That would be awesome !
The wiki is open, you can create a new page and [add a lint to it in this page](https://github.com/silexlabs/Silex/wiki/tutorials-and-guides)
